/**
 * The word each contextual kanji actually lives in.
 *
 * Keyed by `KanjiRow.sense`, so the 120 rows share 98 words (名 and 前 both
 * belong to `namae`). Written 交ぜ書き: only the glyphs this course teaches
 * for *this* sense are in kanji, everything else stays kana, so a learner
 * never meets an untaught glyph. `wordKana` is the whole word's reading and
 * is what the ruby renders above it.
 */
export interface A2ContextualWord {
  /** Mixed kanji/kana orthography, e.g. 友だち. */
  readonly word: string;
  /** The whole word in kana, e.g. ともだち. */
  readonly wordKana: string;
}

export const A2_CONTEXTUAL_WORDS: Readonly<Record<string, A2ContextualWord>> = Object.freeze({
  hanasu: { word: "話す", wordKana: "はなす" },
  iu: { word: "言う", wordKana: "いう" },
  kiku: { word: "聞く", wordKana: "きく" },
  tomodachi: { word: "友だち", wordKana: "ともだち" },
  omou: { word: "思う", wordKana: "おもう" },
  namae: { word: "名前", wordKana: "なまえ" },
  nani: { word: "何", wordKana: "なに" },
  yotei: { word: "予定", wordKana: "よてい" },
  youbi: { word: "曜日", wordKana: "ようび" },
  au: { word: "会う", wordKana: "あう" },
  konshuu: { word: "今週", wordKana: "こんしゅう" },
  shuumatsu: { word: "しゅう末", wordKana: "しゅうまつ" },
  machimasu: { word: "待つ", wordKana: "まつ" },
  yakusoku: { word: "約そく", wordKana: "やくそく" },
  raigetsu: { word: "来月", wordKana: "らいげつ" },
  kyonen: { word: "去年", wordKana: "きょねん" },
  tanoshii: { word: "楽しい", wordKana: "たのしい" },
  hajimete: { word: "初めて", wordKana: "はじめて" },
  ichido: { word: "いち度", wordKana: "いちど" },
  yuumei: { word: "有めい", wordKana: "ゆうめい" },
  oyogu: { word: "泳ぐ", wordKana: "およぐ" },
  noboru: { word: "登る", wordKana: "のぼる" },
  ryokou: { word: "旅こう", wordKana: "りょこう" },
  riyuu: { word: "理由", wordKana: "りゆう" },
  kangaeru: { word: "考える", wordKana: "かんがえる" },
  iken: { word: "意見", wordKana: "いけん" },
  kimochi: { word: "気持ち", wordKana: "きもち" },
  warui: { word: "悪い", wordKana: "わるい" },
  okiru: { word: "起きる", wordKana: "おきる" },
  neru: { word: "寝る", wordKana: "ねる" },
  tsukau: { word: "使う", wordKana: "つかう" },
  tsukuru: { word: "作る", wordKana: "つくる" },
  mainichi: { word: "毎にち", wordKana: "まいにち" },
  arau: { word: "洗う", wordKana: "あらう" },
  owaru: { word: "終わる", wordKana: "おわる" },
  hajimaru: { word: "始まる", wordKana: "はじまる" },
  hataraku: { word: "働く", wordKana: "はたらく" },
  hairu: { word: "入る", wordKana: "はいる" },
  iriguchi: { word: "いり口", wordKana: "いりぐち" },
  deguchi: { word: "出ぐち", wordKana: "でぐち" },
  "tomaru-stop": { word: "止まる", wordKana: "とまる" },
  kinshi: { word: "禁し", wordKana: "きんし" },
  kesu: { word: "消す", wordKana: "けす" },
  suwaru: { word: "座る", wordKana: "すわる" },
  tatsu: { word: "立つ", wordKana: "たつ" },
  byouin: { word: "病院", wordKana: "びょういん" },
  ginkou: { word: "銀行", wordKana: "ぎんこう" },
  yuubinkyoku: { word: "ゆうびん局", wordKana: "ゆうびんきょく" },
  benri: { word: "便り", wordKana: "べんり" },
  toshokan: { word: "図しょ館", wordKana: "としょかん" },
  taberu: { word: "食べる", wordKana: "たべる" },
  nomu: { word: "飲む", wordKana: "のむ" },
  gohan: { word: "ご飯", wordKana: "ごはん" },
  ocha: { word: "お茶", wordKana: "おちゃ" },
  niku: { word: "肉", wordKana: "にく" },
  sakana: { word: "魚", wordKana: "さかな" },
  atsui: { word: "熱い", wordKana: "あつい" },
  tsumetai: { word: "冷たい", wordKana: "つめたい" },
  kau: { word: "買う", wordKana: "かう" },
  mise: { word: "店", wordKana: "みせ" },
  senen: { word: "千円", wordKana: "せんえん" },
  ichiban: { word: "いち番", wordKana: "いちばん" },
  ichiman: { word: "いち万", wordKana: "いちまん" },
  yasui: { word: "安い", wordKana: "やすい" },
  takai: { word: "高い", wordKana: "たかい" },
  isha: { word: "医者", wordKana: "いしゃ" },
  kusuri: { word: "薬", wordKana: "くすり" },
  karada: { word: "体", wordKana: "からだ" },
  atama: { word: "頭", wordKana: "あたま" },
  itai: { word: "痛い", wordKana: "いたい" },
  genki: { word: "元き", wordKana: "げんき" },
  yasumu: { word: "休む", wordKana: "やすむ" },
  kaisha: { word: "かい社", wordKana: "かいしゃ" },
  shigoto: { word: "仕事", wordKana: "しごと" },
  oshieru: { word: "教える", wordKana: "おしえる" },
  gakkou: { word: "学校", wordKana: "がっこう" },
  sensei: { word: "先せい", wordKana: "せんせい" },
  gakusei: { word: "がく生", wordKana: "がくせい" },
  kuukou: { word: "空港", wordKana: "くうこう" },
  eki: { word: "駅", wordKana: "えき" },
  densha: { word: "電車", wordKana: "でんしゃ" },
  yama: { word: "山", wordKana: "やま" },
  "tsuku-arrive": { word: "着く", wordKana: "つく" },
  shuppatsu: { word: "しゅっ発", wordKana: "しゅっぱつ" },
  "tomaru-stay": { word: "泊まる", wordKana: "とまる" },
  haha: { word: "母", wordKana: "はは" },
  chichi: { word: "父", wordKana: "ちち" },
  kazoku: { word: "家族", wordKana: "かぞく" },
  kekkon: { word: "結婚", wordKana: "けっこん" },
  tanjoubi: { word: "誕じょうび", wordKana: "たんじょうび" },
  okuru: { word: "送る", wordKana: "おくる" },
  jikan: { word: "時間", wordKana: "じかん" },
  gofun: { word: "ご分", wordKana: "ごふん" },
  han: { word: "半", wordKana: "はん" },
  hon: { word: "本", wordKana: "ほん" },
  ryoukin: { word: "料金", wordKana: "りょうきん" },
  aku: { word: "開く", wordKana: "あく" },
  shimaru: { word: "閉まる", wordKana: "しまる" },
});
