/**
 * Foundations module 4 — time, past forms, and movement.
 *
 * This authoring slice is part of the published Foundations area.
 */

import { defineA1Module } from "../authoring";
import type { A1ModuleRecipe } from "../types";
import type { VerbUseRecord } from "../../foundations/types";
import {
  A1_AFFIRMATIVE_PAST_POLITE,
  A1_CONCEPT_DIRECTION_HE,
  A1_CONCEPT_TIME_SCHEDULE,
  A1_CONCEPT_TRANSPORT_DE,
  A1_NEGATIVE_PAST_POLITE,
  a1VerbUseRecord,
  buildA1InstructionalLesson,
  type A1BuiltLesson,
  type Bilingual,
} from "./shared";

const MODULE_ID = "time-movement";
const L = (en: string, it: string): Bilingual => ({ en, it });

const SCHEDULE = "a1-family-foundation-schedule-action";
const TIME = "a1-family-foundation-time-action";
const BARE = "a1-family-foundation-bare-action";
const DIRECTION = "a1-family-foundation-direction-action";
const TRANSPORT = "a1-family-foundation-transport-action";

const SELF = "a1-referent-self";
const WATASHI = "a1-value-watashi";

const timed = (subject: string, predicate: string, time: string) => ({
  subject,
  predicate,
  time,
});
const bare = (subject: string, predicate: string) => ({ subject, predicate });
const location = (subject: string, predicate: string, place: string) => ({
  subject,
  predicate,
  location: place,
});
const transport = (
  subject: string,
  predicate: string,
  transportValue: string,
  place: string,
) => ({
  subject,
  predicate,
  transport: transportValue,
  location: place,
});

const PAST_QUESTION = {
  ...A1_AFFIRMATIVE_PAST_POLITE,
  interrogative: true,
} as const;

const lesson1: A1BuiltLesson = buildA1InstructionalLesson({
  id: "time-movement-1",
  moduleId: MODULE_ID,
  order: 1,
  primaryCanDoId: "a1-can-do-time-movement",
  supportingCanDoIds: ["a1-can-do-polite-verbs"],
  introducedConceptIds: [A1_CONCEPT_TIME_SCHEDULE],
  introducedSenseIds: [
    "a1-sense-study-routine",
    "a1-sense-rest-routine",
    "a1-sense-return",
  ],
  diversityOverride: { minPredicates: 2 },
  models: [
    {
      id: "time-movement-1-m1",
      family: SCHEDULE,
      context: "a1-context-routine-study-schedule",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: timed(WATASHI, "a1-value-study-routine", "a1-value-time-6"),
      translation: L("I study at six.", "Studio alle sei."),
    },
    {
      id: "time-movement-1-m2",
      family: SCHEDULE,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: timed("a1-value-yuki", "a1-value-study-routine", "a1-value-time-7"),
      translation: L("Yuki studies at seven.", "Yuki studia alle sette."),
    },
    {
      id: "time-movement-1-m3",
      family: SCHEDULE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: timed("a1-value-ken", "a1-value-return", "a1-value-time-8"),
      translation: L("Ken returns at eight.", "Ken torna alle otto."),
    },
    {
      id: "time-movement-1-m4",
      family: SCHEDULE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: timed("a1-value-mina", "a1-value-return", "a1-value-time-9"),
      translation: L("Mina returns at nine.", "Mina torna alle nove."),
    },
    {
      id: "time-movement-1-m5",
      family: SCHEDULE,
      context: "a1-context-routine-study-schedule",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: timed(WATASHI, "a1-value-study-routine", "a1-value-time-8"),
      translation: L("I study at eight.", "Studio alle otto."),
    },
    {
      id: "time-movement-1-m6",
      family: SCHEDULE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: timed("a1-value-yuki", "a1-value-return", "a1-value-time-7"),
      translation: L("Yuki returns at seven.", "Yuki torna alle sette."),
    },
    {
      id: "time-movement-1-m7",
      family: SCHEDULE,
      context: "a1-context-rest-routine",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: timed("a1-value-ken", "a1-value-rest-routine", "a1-value-time-9"),
      translation: L("Ken takes a break at nine.", "Ken fa una pausa alle nove."),
    },
    {
      id: "time-movement-1-m8",
      family: SCHEDULE,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: timed("a1-value-mina", "a1-value-return", "a1-value-time-6"),
      translation: L("Mina returns at six.", "Mina torna alle sei."),
    },
  ],
  transfers: [
    {
      id: "time-movement-1-t1",
      family: SCHEDULE,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: timed("a1-value-yuki", "a1-value-study-routine", "a1-value-time-6"),
      translation: L("Yuki studies at six.", "Yuki studia alle sei."),
    },
    {
      id: "time-movement-1-t2",
      family: SCHEDULE,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: timed("a1-value-ken", "a1-value-study-routine", "a1-value-time-7"),
      translation: L("Ken studies at seven.", "Ken studia alle sette."),
    },
    {
      id: "time-movement-1-t3",
      family: SCHEDULE,
      context: "a1-context-home",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: timed(WATASHI, "a1-value-return", "a1-value-time-8"),
      translation: L("I return at eight.", "Torno alle otto."),
    },
    {
      id: "time-movement-1-t4",
      family: SCHEDULE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: timed("a1-value-mina", "a1-value-return", "a1-value-time-7"),
      translation: L("Mina returns at seven.", "Mina torna alle sette."),
    },
    {
      id: "time-movement-1-t5",
      family: SCHEDULE,
      context: "a1-context-routine-study-schedule",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: timed(WATASHI, "a1-value-study-routine", "a1-value-time-9"),
      translation: L("I study at nine.", "Studio alle nove."),
    },
  ],
});

const lesson2: A1BuiltLesson = buildA1InstructionalLesson({
  id: "time-movement-2",
  moduleId: MODULE_ID,
  order: 2,
  primaryCanDoId: "a1-can-do-time-movement",
  supportingCanDoIds: ["a1-can-do-polite-verbs"],
  introducedConceptIds: [],
  introducedSenseIds: [],
  diversityOverride: { minPredicates: 2 },
  models: [
    {
      id: "time-movement-2-m1",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed(WATASHI, "a1-value-study-routine", "a1-value-seq-morning"),
      translation: L("I studied in the morning.", "Ho studiato la mattina."),
    },
    {
      id: "time-movement-2-m2",
      family: TIME,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-yuki", "a1-value-return", "a1-value-seq-noon"),
      translation: L("Yuki returned at noon.", "Yuki è tornata a mezzogiorno."),
    },
    {
      id: "time-movement-2-m3",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-ken", "a1-value-study-routine", "a1-value-seq-evening"),
      translation: L("Ken studied in the evening.", "Ken ha studiato la sera."),
    },
    {
      id: "time-movement-2-m4",
      family: TIME,
      context: "a1-context-home",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-mina", "a1-value-return", "a1-value-seq-night"),
      translation: L("Mina returned at night.", "Mina è tornata di notte."),
    },
    {
      id: "time-movement-2-m5",
      family: TIME,
      context: "a1-context-classroom",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed(WATASHI, "a1-value-return", "a1-value-seq-morning"),
      translation: L("I returned in the morning.", "Sono tornato la mattina."),
    },
    {
      id: "time-movement-2-m6",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-yuki", "a1-value-study-routine", "a1-value-seq-noon"),
      translation: L("Yuki studied at noon.", "Yuki ha studiato a mezzogiorno."),
    },
    {
      id: "time-movement-2-m7",
      family: TIME,
      context: "a1-context-home",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-ken", "a1-value-return", "a1-value-seq-evening"),
      translation: L("Ken returned in the evening.", "Ken è tornato la sera."),
    },
    {
      id: "time-movement-2-m8",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-mina", "a1-value-study-routine", "a1-value-seq-night"),
      translation: L("Mina studied at night.", "Mina ha studiato di notte."),
    },
  ],
  transfers: [
    {
      id: "time-movement-2-t1",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-yuki", "a1-value-study-routine", "a1-value-seq-morning"),
      translation: L("Yuki studied in the morning.", "Yuki ha studiato la mattina."),
    },
    {
      id: "time-movement-2-t2",
      family: TIME,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-ken", "a1-value-return", "a1-value-seq-noon"),
      translation: L("Ken returned at noon.", "Ken è tornato a mezzogiorno."),
    },
    {
      id: "time-movement-2-t3",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed(WATASHI, "a1-value-study-routine", "a1-value-seq-evening"),
      translation: L("I studied in the evening.", "Ho studiato la sera."),
    },
    {
      id: "time-movement-2-t4",
      family: TIME,
      context: "a1-context-home",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-yuki", "a1-value-return", "a1-value-seq-night"),
      translation: L("Yuki returned at night.", "Yuki è tornata di notte."),
    },
    {
      id: "time-movement-2-t5",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: timed("a1-value-ken", "a1-value-study-routine", "a1-value-seq-night"),
      translation: L("Ken studied at night.", "Ken ha studiato di notte."),
    },
  ],
});

const lesson3: A1BuiltLesson = buildA1InstructionalLesson({
  id: "time-movement-3",
  moduleId: MODULE_ID,
  order: 3,
  primaryCanDoId: "a1-can-do-time-movement",
  supportingCanDoIds: ["a1-can-do-polite-verbs"],
  introducedConceptIds: [],
  introducedSenseIds: [],
  models: [
    {
      id: "time-movement-3-m1",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: timed(WATASHI, "a1-value-study-routine", "a1-value-time-yesterday"),
      translation: L("I did not study yesterday.", "Ieri non ho studiato."),
    },
    {
      id: "time-movement-3-m2",
      family: TIME,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: timed("a1-value-yuki", "a1-value-return", "a1-value-time-today"),
      translation: L("Yuki did not return today.", "Yuki oggi non è tornata."),
    },
    {
      id: "time-movement-3-m3",
      family: TIME,
      context: "a1-context-routine-study-schedule",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: timed("a1-value-ken", "a1-value-study-routine", "a1-value-time-last-week"),
      translation: L("Ken did not study last week.", "Ken non ha studiato la settimana scorsa."),
    },
    {
      id: "time-movement-3-m4",
      family: TIME,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: timed(
        "a1-value-mina",
        "a1-value-return",
        "a1-value-time-day-before-yesterday",
      ),
      translation: L(
        "Mina did not return the day before yesterday.",
        "Mina non è tornata l'altro ieri.",
      ),
    },
    {
      id: "time-movement-3-m5",
      family: BARE,
      context: "a1-context-bare-return-response",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare(WATASHI, "a1-value-return-bare"),
      translation: L("I did not return.", "Non sono tornato."),
    },
    {
      id: "time-movement-3-m6",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare("a1-value-yuki", "a1-value-go-bare"),
      translation: L("Yuki did not go.", "Yuki non è andata."),
    },
    {
      id: "time-movement-3-m7",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare("a1-value-ken", "a1-value-rest-bare"),
      translation: L("Ken did not take a break.", "Ken non ha fatto una pausa."),
    },
    {
      id: "time-movement-3-m8",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare("a1-value-mina", "a1-value-rest-bare"),
      translation: L("Mina did not take a break.", "Mina non ha fatto una pausa."),
    },
  ],
  transfers: [
    {
      id: "time-movement-3-t1",
      family: BARE,
      context: "a1-context-workplace",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare(WATASHI, "a1-value-work-bare"),
      translation: L("I did not work.", "Non ho lavorato."),
    },
    {
      id: "time-movement-3-t2",
      family: BARE,
      context: "a1-context-bare-study-conversation",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare("a1-value-yuki", "a1-value-study-bare"),
      translation: L("Yuki did not study.", "Yuki non ha studiato."),
    },
    {
      id: "time-movement-3-t3",
      family: BARE,
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare("a1-value-ken", "a1-value-do-bare"),
      translation: L("Ken did not do it.", "Ken non l'ha fatto."),
    },
    {
      id: "time-movement-3-t4",
      family: BARE,
      context: "a1-context-bare-return-response",
      subjectReferent: SELF,
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare(WATASHI, "a1-value-return-bare"),
      translation: L("I did not return.", "Non sono tornato."),
    },
    {
      id: "time-movement-3-t5",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_NEGATIVE_PAST_POLITE,
      slots: bare("a1-value-ken", "a1-value-go-bare"),
      translation: L("Ken did not go.", "Ken non è andato."),
    },
  ],
});

const lesson4: A1BuiltLesson = buildA1InstructionalLesson({
  id: "time-movement-4",
  moduleId: MODULE_ID,
  order: 4,
  primaryCanDoId: "a1-can-do-time-movement",
  supportingCanDoIds: ["a1-can-do-polite-verbs"],
  introducedConceptIds: [A1_CONCEPT_DIRECTION_HE, A1_CONCEPT_TRANSPORT_DE],
  introducedSenseIds: [],
  diversityOverride: { minPredicates: 2 },
  models: [
    {
      id: "time-movement-4-m1",
      family: DIRECTION,
      context: "a1-context-station",
      subjectReferent: "a1-referent-teacher",
      subjectRealization: "omitted",
      form: PAST_QUESTION,
      speakerRole: "a1-role-learner",
      addresseeRole: "a1-role-teacher",
      slots: location("a1-value-anata", "a1-value-go", "a1-value-loc-doko"),
      translation: L("Where did you go?", "Dove sei andato?"),
    },
    {
      id: "time-movement-4-m2",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      speakerRole: "a1-role-teacher",
      addresseeRole: "a1-role-learner",
      slots: transport(
        WATASHI,
        "a1-value-go",
        "a1-value-transport-train",
        "a1-value-loc-station",
      ),
      translation: L("I went to the station by train.", "Sono andato alla stazione in treno."),
    },
    {
      id: "time-movement-4-m3",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        "a1-value-yuki",
        "a1-value-return-location",
        "a1-value-transport-bus",
        "a1-value-loc-company",
      ),
      translation: L("Yuki returned to the company by bus.", "Yuki è tornata in azienda in autobus."),
    },
    {
      id: "time-movement-4-m4",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        "a1-value-ken",
        "a1-value-go",
        "a1-value-transport-bicycle",
        "a1-value-loc-school",
      ),
      translation: L("Ken went to school by bicycle.", "Ken è andato a scuola in bicicletta."),
    },
    {
      id: "time-movement-4-m5",
      family: DIRECTION,
      context: "a1-context-station",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: location(WATASHI, "a1-value-go", "a1-value-loc-library"),
      translation: L("I went toward the library.", "Sono andato verso la biblioteca."),
    },
    {
      id: "time-movement-4-m6",
      family: TRANSPORT,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        "a1-value-mina",
        "a1-value-go",
        "a1-value-transport-train",
        "a1-value-loc-cafe",
      ),
      translation: L("Mina went to the cafe by train.", "Mina è andata al bar in treno."),
    },
    {
      id: "time-movement-4-m7",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        WATASHI,
        "a1-value-go",
        "a1-value-transport-bus",
        "a1-value-loc-library",
      ),
      translation: L("I went to the library by bus.", "Sono andato in biblioteca in autobus."),
    },
    {
      id: "time-movement-4-m8",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        "a1-value-yuki",
        "a1-value-return-location",
        "a1-value-transport-bicycle",
        "a1-value-loc-company",
      ),
      translation: L("Yuki returned to the company by bicycle.", "Yuki è tornata in azienda in bicicletta."),
    },
  ],
  transfers: [
    {
      id: "time-movement-4-t1",
      family: DIRECTION,
      context: "a1-context-station",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: location("a1-value-ken", "a1-value-go", "a1-value-loc-station"),
      translation: L("Ken went toward the station.", "Ken è andato verso la stazione."),
    },
    {
      id: "time-movement-4-t2",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        WATASHI,
        "a1-value-return-location",
        "a1-value-transport-train",
        "a1-value-loc-company",
      ),
      translation: L("I returned to the company by train.", "Sono tornato in azienda in treno."),
    },
    {
      id: "time-movement-4-t3",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        "a1-value-mina",
        "a1-value-go",
        "a1-value-transport-bus",
        "a1-value-loc-school",
      ),
      translation: L("Mina went to school by bus.", "Mina è andata a scuola in autobus."),
    },
    {
      id: "time-movement-4-t4",
      family: TRANSPORT,
      context: "a1-context-station",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: transport(
        "a1-value-ken",
        "a1-value-go",
        "a1-value-transport-bicycle",
        "a1-value-loc-library",
      ),
      translation: L("Ken went to the library by bicycle.", "Ken è andato in biblioteca in bicicletta."),
    },
    {
      id: "time-movement-4-t5",
      family: DIRECTION,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: A1_AFFIRMATIVE_PAST_POLITE,
      slots: location(WATASHI, "a1-value-go", "a1-value-loc-cafe"),
      translation: L("I went toward the cafe.", "Sono andato verso il bar."),
    },
  ],
});

export const moduleTimeMovementLessons: readonly A1BuiltLesson[] = [
  lesson1,
  lesson2,
  lesson3,
  lesson4,
];

export const moduleTimeMovementRecipe: A1ModuleRecipe = defineA1Module({
  id: MODULE_ID,
  order: 5,
  prerequisiteIds: ["polite-verbs"],
  lessonIds: moduleTimeMovementLessons.map(({ recipe }) => recipe.id),
  outcomeCopyId: "a1-module-outcome-time-movement",
});

/** Canonical recurrence records for the published time-movement lessons. */
export const moduleTimeMovementVerbUseRecords: readonly VerbUseRecord[] = [
  a1VerbUseRecord({
    senseId: "a1-sense-study-routine",
    introductionLessonId: "time-movement-1",
    introductionVariantIds: ["time-movement-1-m2", "time-movement-1-m5"],
    exerciseRoundId: "time-movement-1-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "time-movement-1-m2",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-return",
    introductionLessonId: "time-movement-1",
    introductionVariantIds: ["time-movement-1-m3", "time-movement-1-m6"],
    exerciseRoundId: "time-movement-1-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "time-movement-1-m3",
  }),
];
