/**
 * Foundations module 1 — predicate-final identity sentences.
 *
 * This authoring slice is part of the published Foundations area.
 */

import { defineA1Module } from "../authoring";
import type { A1ModuleRecipe } from "../types";
import type { VerbUseRecord } from "../../foundations/types";
import {
  A1_CONCEPT_COPULA_DESU,
  A1_CONCEPT_TOPIC_WA,
  a1VerbUseRecord,
  buildA1InstructionalLesson,
  type A1BuiltLesson,
  type Bilingual,
} from "./shared";

const MODULE_ID = "sentence-foundations";
const L = (en: string, it: string): Bilingual => ({ en, it });

const cop = (subject: string, object: string) => ({
  subject,
  predicate: "a1-value-be",
  object,
});

const lesson1: A1BuiltLesson = buildA1InstructionalLesson({
  id: "sentence-foundations-1",
  moduleId: MODULE_ID,
  order: 1,
  primaryCanDoId: "a1-can-do-sentence-foundations",
  supportingCanDoIds: [],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [A1_CONCEPT_TOPIC_WA, A1_CONCEPT_COPULA_DESU],
  introducedSenseIds: ["a1-sense-be"],
  models: [
    {
      id: "sentence-foundations-1-m1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-self",
      subjectRealization: "explicit",
      slots: cop("a1-value-watashi", "a1-value-obj-student"),
      translation: L("I am a student.", "Sono uno studente."),
      speakerRole: "a1-role-learner",
    },
    {
      id: "sentence-foundations-1-m2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-self",
      subjectRealization: "explicit",
      slots: cop("a1-value-watashi", "a1-value-obj-teacher"),
      translation: L("I am a teacher.", "Sono un insegnante."),
      speakerRole: "a1-role-teacher",
    },
    {
      id: "sentence-foundations-1-m3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-kore", "a1-value-obj-student"),
      translation: L("This is a student.", "Questo è uno studente."),
      speakerRole: "a1-role-classmate",
    },
    {
      id: "sentence-foundations-1-m4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-student"),
      translation: L("I am a student.", "Sono uno studente."),
      speakerRole: "a1-role-learner",
    },
    {
      id: "sentence-foundations-1-m5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-teacher",
      subjectRealization: "explicit",
      slots: cop("a1-value-teacher-subject", "a1-value-obj-student"),
      translation: L("The teacher is a student.", "L'insegnante è uno studente."),
      speakerRole: "a1-role-teacher",
    },
    {
      id: "sentence-foundations-1-m6",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-student"),
      translation: L("I am a student.", "Sono uno studente."),
      speakerRole: "a1-role-classmate",
    },
    {
      id: "sentence-foundations-1-m7",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-teacher"),
      translation: L("I am a teacher.", "Sono un insegnante."),
      speakerRole: "a1-role-person",
    },
    {
      id: "sentence-foundations-1-m8",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-kore", "a1-value-obj-teacher"),
      translation: L("This is a teacher.", "Questo è un insegnante."),
      speakerRole: "a1-role-learner",
    },
  ],
  transfers: [
    {
      id: "sentence-foundations-1-t1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-student"),
      translation: L("I am a student.", "Sono uno studente."),
      speakerRole: "a1-role-clerk",
    },
    {
      id: "sentence-foundations-1-t2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-self",
      subjectRealization: "explicit",
      slots: cop("a1-value-watashi", "a1-value-obj-teacher"),
      translation: L("I am a teacher.", "Sono un insegnante."),
      speakerRole: "a1-role-clerk",
    },
    {
      id: "sentence-foundations-1-t3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-student"),
      translation: L("This is a student.", "Questo è uno studente."),
      speakerRole: "a1-role-friend",
    },
    {
      id: "sentence-foundations-1-t4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-self",
      subjectRealization: "explicit",
      slots: cop("a1-value-watashi", "a1-value-obj-student"),
      translation: L("I am a student.", "Sono uno studente."),
      speakerRole: "a1-role-person",
    },
    {
      id: "sentence-foundations-1-t5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-teacher"),
      translation: L("I am a teacher.", "Sono un insegnante."),
      speakerRole: "a1-role-clerk",
    },
  ],
});

const lesson2: A1BuiltLesson = buildA1InstructionalLesson({
  id: "sentence-foundations-2",
  moduleId: MODULE_ID,
  order: 2,
  primaryCanDoId: "a1-can-do-sentence-foundations",
  supportingCanDoIds: [],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [],
  introducedSenseIds: [],
  models: [
    {
      id: "sentence-foundations-2-m1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-student"),
      translation: L("Yuki is a student.", "Yuki è una studentessa."),
    },
    {
      id: "sentence-foundations-2-m2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: cop("a1-value-ken", "a1-value-obj-teacher"),
      translation: L("Ken is a teacher.", "Ken è un insegnante."),
    },
    {
      id: "sentence-foundations-2-m3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-student"),
      translation: L("Mina is a student.", "Mina è una studentessa."),
    },
    {
      id: "sentence-foundations-2-m4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-kore", "a1-value-obj-name"),
      translation: L("This is a name.", "Questo è un nome."),
    },
    {
      id: "sentence-foundations-2-m5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: cop("a1-value-yuki", "a1-value-obj-student"),
      translation: L("Yuki is a student.", "Yuki è una studentessa."),
    },
    {
      id: "sentence-foundations-2-m6",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      slots: cop("a1-value-ken", "a1-value-obj-teacher"),
      translation: L("Ken is a teacher.", "Ken è un insegnante."),
    },
    {
      id: "sentence-foundations-2-m7",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "omitted",
      slots: cop("a1-value-mina", "a1-value-obj-student"),
      translation: L("Mina is a student.", "Mina è una studentessa."),
    },
    {
      id: "sentence-foundations-2-m8",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-name"),
      translation: L("This is a name.", "Questo è un nome."),
    },
  ],
  transfers: [
    {
      id: "sentence-foundations-2-t1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-teacher"),
      translation: L("Yuki is a teacher.", "Yuki è un'insegnante."),
    },
    {
      id: "sentence-foundations-2-t2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      slots: cop("a1-value-ken", "a1-value-obj-student"),
      translation: L("Ken is a student.", "Ken è uno studente."),
    },
    {
      id: "sentence-foundations-2-t3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-teacher"),
      translation: L("Mina is a teacher.", "Mina è un'insegnante."),
    },
    {
      id: "sentence-foundations-2-t4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-name"),
      translation: L("This is a name.", "Questo è un nome."),
    },
    {
      id: "sentence-foundations-2-t5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: cop("a1-value-yuki", "a1-value-obj-student"),
      translation: L("Yuki is a student.", "Yuki è una studentessa."),
    },
  ],
});

const lesson3: A1BuiltLesson = buildA1InstructionalLesson({
  id: "sentence-foundations-3",
  moduleId: MODULE_ID,
  order: 3,
  primaryCanDoId: "a1-can-do-sentence-foundations",
  supportingCanDoIds: [],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [],
  introducedSenseIds: [],
  models: [
    {
      id: "sentence-foundations-3-m1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-unidentified-addressee",
      subjectReferent: "a1-referent-unidentified-addressee",
      subjectRealization: "explicit",
      slots: cop("a1-value-anata", "a1-value-obj-student"),
      translation: L("You are a student.", "Tu sei uno studente."),
      speakerRole: "a1-role-learner",
      addresseeRole: "a1-role-unidentified-addressee",
    },
    {
      id: "sentence-foundations-3-m2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-kono-hito", "a1-value-obj-student"),
      translation: L("This person is a student.", "Questa persona è una studentessa."),
    },
    {
      id: "sentence-foundations-3-m3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-sono-hito", "a1-value-obj-teacher"),
      translation: L("That person is a teacher.", "Quella persona è un insegnante."),
    },
    {
      id: "sentence-foundations-3-m4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-ano-hito", "a1-value-obj-student"),
      translation: L("That person over there is a student.", "Quella persona laggiù è uno studente."),
    },
    {
      id: "sentence-foundations-3-m5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-teacher"),
      translation: L("Yuki is a teacher.", "Yuki è un'insegnante."),
    },
    {
      id: "sentence-foundations-3-m6",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: cop("a1-value-ken", "a1-value-obj-student"),
      translation: L("Ken is a student.", "Ken è uno studente."),
    },
    {
      id: "sentence-foundations-3-m7",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-teacher"),
      translation: L("Mina is a teacher.", "Mina è un'insegnante."),
    },
    {
      id: "sentence-foundations-3-m8",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: cop("a1-value-yuki", "a1-value-obj-student"),
      translation: L("Yuki is a student.", "Yuki è una studentessa."),
    },
  ],
  transfers: [
    {
      id: "sentence-foundations-3-t1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-kono-hito", "a1-value-obj-teacher"),
      translation: L("This person is a teacher.", "Questa persona è un insegnante."),
    },
    {
      id: "sentence-foundations-3-t2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-sono-hito", "a1-value-obj-student"),
      translation: L("That person is a student.", "Quella persona è una studentessa."),
    },
    {
      id: "sentence-foundations-3-t3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-ano-hito", "a1-value-obj-teacher"),
      translation: L("That person over there is a teacher.", "Quella persona laggiù è un insegnante."),
    },
    {
      id: "sentence-foundations-3-t4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      slots: cop("a1-value-ken", "a1-value-obj-teacher"),
      translation: L("Ken is a teacher.", "Ken è un insegnante."),
    },
    {
      id: "sentence-foundations-3-t5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "omitted",
      slots: cop("a1-value-mina", "a1-value-obj-student"),
      translation: L("Mina is a student.", "Mina è una studentessa."),
    },
  ],
});

const lesson4: A1BuiltLesson = buildA1InstructionalLesson({
  id: "sentence-foundations-4",
  moduleId: MODULE_ID,
  order: 4,
  primaryCanDoId: "a1-can-do-sentence-foundations",
  supportingCanDoIds: [],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [],
  introducedSenseIds: [],
  models: [
    {
      id: "sentence-foundations-4-m1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-self",
      subjectRealization: "explicit",
      slots: cop("a1-value-watashi", "a1-value-obj-doctor"),
      translation: L("I am a doctor.", "Sono un medico."),
      speakerRole: "a1-role-learner",
    },
    {
      id: "sentence-foundations-4-m2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-office-worker"),
      translation: L("I am an office worker.", "Sono un impiegato."),
      speakerRole: "a1-role-friend",
    },
    {
      id: "sentence-foundations-4-m3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: cop("a1-value-ken", "a1-value-obj-engineer"),
      translation: L("Ken is an engineer.", "Ken è un ingegnere."),
    },
    {
      id: "sentence-foundations-4-m4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-classmate-peer"),
      translation: L("Mina is a classmate.", "Mina è una compagna di corso."),
    },
    {
      id: "sentence-foundations-4-m5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-doctor"),
      translation: L("I am a doctor.", "Sono un medico."),
      speakerRole: "a1-role-learner",
    },
    {
      id: "sentence-foundations-4-m6",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-engineer"),
      translation: L("I am an engineer.", "Sono un ingegnere."),
      speakerRole: "a1-role-classmate",
    },
    {
      id: "sentence-foundations-4-m7",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-classmate-peer"),
      translation: L("I am a classmate.", "Sono un compagno di corso."),
      speakerRole: "a1-role-learner",
    },
    {
      id: "sentence-foundations-4-m8",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-self",
      subjectRealization: "explicit",
      slots: cop("a1-value-watashi", "a1-value-obj-office-worker"),
      translation: L("I am an office worker.", "Sono un impiegato."),
      speakerRole: "a1-role-classmate",
    },
  ],
  transfers: [
    {
      id: "sentence-foundations-4-t1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-office-worker"),
      translation: L("Yuki is an office worker.", "Yuki è un'impiegata."),
    },
    {
      id: "sentence-foundations-4-t2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      slots: cop("a1-value-ken", "a1-value-obj-engineer"),
      translation: L("Ken is an engineer.", "Ken è un ingegnere."),
    },
    {
      id: "sentence-foundations-4-t3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "omitted",
      slots: cop("a1-value-mina", "a1-value-obj-classmate-peer"),
      translation: L("Mina is a classmate.", "Mina è una compagna di corso."),
    },
    {
      id: "sentence-foundations-4-t4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-self",
      subjectRealization: "explicit",
      slots: cop("a1-value-watashi", "a1-value-obj-doctor"),
      translation: L("I am a doctor.", "Sono un medico."),
      speakerRole: "a1-role-learner",
    },
    {
      id: "sentence-foundations-4-t5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-self",
      subjectRealization: "omitted",
      slots: cop("a1-value-watashi", "a1-value-obj-office-worker"),
      translation: L("I am an office worker.", "Sono un impiegato."),
      speakerRole: "a1-role-person",
    },
  ],
});

export const moduleSentenceFoundationsLessons: readonly A1BuiltLesson[] = [
  lesson1,
  lesson2,
  lesson3,
  lesson4,
];

export const moduleSentenceFoundationsRecipe: A1ModuleRecipe = defineA1Module({
  id: MODULE_ID,
  order: 2,
  prerequisiteIds: ["sounds"],
  lessonIds: moduleSentenceFoundationsLessons.map(({ recipe }) => recipe.id),
  outcomeCopyId: "a1-module-outcome-sentence-foundations",
});

/** Canonical recurrence records for the published sentence-foundations lessons. */
export const moduleSentenceFoundationsVerbUseRecords: readonly VerbUseRecord[] = [
  a1VerbUseRecord({
    senseId: "a1-sense-be",
    introductionLessonId: "sentence-foundations-1",
    introductionVariantIds: [
      "sentence-foundations-1-m1",
      "sentence-foundations-1-m4",
    ],
    exerciseRoundId: "sentence-foundations-1-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "sentence-foundations-1-m1",
  }),
];
