/**
 * Staged Foundations module 3 — polite nonpast verbs and place particles.
 *
 * This authoring slice deliberately stays outside the published 12-module A1
 * catalog until Task 5 promotes the complete Foundations area.
 */

import { defineA1Module } from "../authoring";
import type { A1ModuleRecipe } from "../types";
import type { VerbUseRecord } from "../../foundations/types";
import {
  A1_CONCEPT_LOCATION_PARTICLE,
  A1_CONCEPT_OBJECT_WO,
  a1VerbUseRecord,
  buildA1InstructionalLesson,
  type A1BuiltLesson,
  type Bilingual,
} from "./shared";

const MODULE_ID = "polite-verbs";
const L = (en: string, it: string): Bilingual => ({ en, it });

const BARE = "a1-family-foundation-bare-action";
const OBJECT = "a1-family-foundation-object-action";
const LOCATION = "a1-family-foundation-location-action";

const SELF = "a1-referent-self";
const WATASHI = "a1-value-watashi";

const bare = (subject: string, predicate: string) => ({ subject, predicate });
const object = (subject: string, predicate: string, objectValue: string) => ({
  subject,
  predicate,
  object: objectValue,
});
const location = (subject: string, predicate: string, place: string) => ({
  subject,
  predicate,
  location: place,
});

const lesson1: A1BuiltLesson = buildA1InstructionalLesson({
  id: "polite-verbs-1",
  moduleId: MODULE_ID,
  order: 1,
  primaryCanDoId: "a1-can-do-polite-verbs",
  supportingCanDoIds: ["a1-can-do-topic-questions"],
  introducedConceptIds: [],
  introducedSenseIds: [
    "a1-sense-work-bare",
    "a1-sense-study-bare",
    "a1-sense-do-bare",
    "a1-sense-rest-bare",
  ],
  models: [
    {
      id: "polite-verbs-1-m1",
      family: BARE,
      context: "a1-context-workplace",
      subjectReferent: SELF,
      subjectRealization: "explicit",
      slots: bare(WATASHI, "a1-value-work-bare"),
      translation: L("I work.", "Lavoro."),
    },
    {
      id: "polite-verbs-1-m2",
      family: BARE,
      context: "a1-context-classroom",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: bare(WATASHI, "a1-value-study-bare"),
      translation: L("I study.", "Studio."),
    },
    {
      id: "polite-verbs-1-m3",
      family: BARE,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: bare("a1-value-mina", "a1-value-do-bare"),
      translation: L("Mina does it.", "Mina lo fa."),
    },
    {
      id: "polite-verbs-1-m4",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: bare(WATASHI, "a1-value-rest-bare"),
      translation: L("I take a break.", "Faccio una pausa."),
    },
    {
      id: "polite-verbs-1-m5",
      family: BARE,
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: bare("a1-value-yuki", "a1-value-work-bare"),
      translation: L("Yuki works.", "Yuki lavora."),
    },
    {
      id: "polite-verbs-1-m6",
      family: BARE,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: bare("a1-value-ken", "a1-value-study-bare"),
      translation: L("Ken studies.", "Ken studia."),
    },
    {
      id: "polite-verbs-1-m7",
      family: BARE,
      context: "a1-context-first-meeting",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: bare(WATASHI, "a1-value-do-bare"),
      translation: L("I do it.", "Lo faccio."),
    },
    {
      id: "polite-verbs-1-m8",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: bare("a1-value-mina", "a1-value-rest-bare"),
      translation: L("Mina takes a break.", "Mina fa una pausa."),
    },
  ],
  transfers: [
    {
      id: "polite-verbs-1-t1",
      family: BARE,
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: bare("a1-value-ken", "a1-value-work-bare"),
      translation: L("Ken works.", "Ken lavora."),
    },
    {
      id: "polite-verbs-1-t2",
      family: BARE,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: bare("a1-value-yuki", "a1-value-study-bare"),
      translation: L("Yuki studies.", "Yuki studia."),
    },
    {
      id: "polite-verbs-1-t3",
      family: BARE,
      context: "a1-context-first-meeting",
      subjectReferent: SELF,
      subjectRealization: "explicit",
      slots: bare(WATASHI, "a1-value-do-bare"),
      translation: L("I do it.", "Lo faccio."),
    },
    {
      id: "polite-verbs-1-t4",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: bare("a1-value-yuki", "a1-value-rest-bare"),
      translation: L("Yuki takes a break.", "Yuki fa una pausa."),
    },
    {
      id: "polite-verbs-1-t5",
      family: BARE,
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: bare("a1-value-mina", "a1-value-work-bare"),
      translation: L("Mina works.", "Mina lavora."),
    },
  ],
});

const lesson2: A1BuiltLesson = buildA1InstructionalLesson({
  id: "polite-verbs-2",
  moduleId: MODULE_ID,
  order: 2,
  primaryCanDoId: "a1-can-do-polite-verbs",
  supportingCanDoIds: ["a1-can-do-topic-questions"],
  introducedConceptIds: [A1_CONCEPT_OBJECT_WO],
  introducedSenseIds: [
    "a1-sense-eat",
    "a1-sense-drink",
    "a1-sense-read",
    "a1-sense-write",
  ],
  models: [
    {
      id: "polite-verbs-2-m1",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: object(WATASHI, "a1-value-eat", "a1-value-obj-bread"),
      translation: L("I eat bread.", "Mangio pane."),
    },
    {
      id: "polite-verbs-2-m2",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: object("a1-value-yuki", "a1-value-drink", "a1-value-obj-water"),
      translation: L("Yuki drinks water.", "Yuki beve acqua."),
    },
    {
      id: "polite-verbs-2-m3",
      family: OBJECT,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: object("a1-value-ken", "a1-value-read", "a1-value-obj-book"),
      translation: L("Ken reads a book.", "Ken legge un libro."),
    },
    {
      id: "polite-verbs-2-m4",
      family: OBJECT,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: object("a1-value-mina", "a1-value-write", "a1-value-obj-letter"),
      translation: L("Mina writes a letter.", "Mina scrive una lettera."),
    },
    {
      id: "polite-verbs-2-m5",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "explicit",
      slots: object(WATASHI, "a1-value-eat", "a1-value-obj-sushi"),
      translation: L("I eat sushi.", "Mangio sushi."),
    },
    {
      id: "polite-verbs-2-m6",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: object(WATASHI, "a1-value-drink", "a1-value-obj-tea"),
      translation: L("I drink tea.", "Bevo tè."),
    },
    {
      id: "polite-verbs-2-m7",
      family: OBJECT,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: object("a1-value-yuki", "a1-value-read", "a1-value-obj-newspaper"),
      translation: L("Yuki reads a newspaper.", "Yuki legge un giornale."),
    },
    {
      id: "polite-verbs-2-m8",
      family: OBJECT,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      slots: object("a1-value-ken", "a1-value-write", "a1-value-obj-homework"),
      translation: L("Ken writes homework.", "Ken scrive i compiti."),
    },
  ],
  transfers: [
    {
      id: "polite-verbs-2-t1",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: object("a1-value-mina", "a1-value-eat", "a1-value-obj-ramen"),
      translation: L("Mina eats ramen.", "Mina mangia ramen."),
    },
    {
      id: "polite-verbs-2-t2",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "explicit",
      slots: object(WATASHI, "a1-value-drink", "a1-value-obj-coffee"),
      translation: L("I drink coffee.", "Bevo caffè."),
    },
    {
      id: "polite-verbs-2-t3",
      family: OBJECT,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: object("a1-value-yuki", "a1-value-read", "a1-value-obj-letter"),
      translation: L("Yuki reads a letter.", "Yuki legge una lettera."),
    },
    {
      id: "polite-verbs-2-t4",
      family: OBJECT,
      context: "a1-context-classroom",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: object(WATASHI, "a1-value-write", "a1-value-obj-book"),
      translation: L("I write a book.", "Scrivo un libro."),
    },
    {
      id: "polite-verbs-2-t5",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: object("a1-value-ken", "a1-value-eat", "a1-value-obj-bread"),
      translation: L("Ken eats bread.", "Ken mangia pane."),
    },
  ],
});

const lesson3: A1BuiltLesson = buildA1InstructionalLesson({
  id: "polite-verbs-3",
  moduleId: MODULE_ID,
  order: 3,
  primaryCanDoId: "a1-can-do-polite-verbs",
  supportingCanDoIds: ["a1-can-do-topic-questions"],
  introducedConceptIds: [],
  introducedSenseIds: [
    "a1-sense-see",
    "a1-sense-listen",
    "a1-sense-buy",
    "a1-sense-return-bare",
  ],
  models: [
    {
      id: "polite-verbs-3-m1",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: object(WATASHI, "a1-value-see", "a1-value-obj-movie"),
      translation: L("I do not watch a movie.", "Non guardo un film."),
    },
    {
      id: "polite-verbs-3-m2",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: object("a1-value-yuki", "a1-value-listen", "a1-value-obj-music"),
      translation: L("Yuki does not listen to music.", "Yuki non ascolta la musica."),
    },
    {
      id: "polite-verbs-3-m3",
      family: OBJECT,
      context: "a1-context-shop",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: object("a1-value-ken", "a1-value-buy", "a1-value-obj-bag"),
      translation: L("Ken does not buy a bag.", "Ken non compra una borsa."),
    },
    {
      id: "polite-verbs-3-m4",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: bare("a1-value-mina", "a1-value-return-bare"),
      translation: L("Mina does not return.", "Mina non torna."),
    },
    {
      id: "polite-verbs-3-m5",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: object("a1-value-yuki", "a1-value-see", "a1-value-obj-photo"),
      translation: L("Yuki does not look at a photo.", "Yuki non guarda una foto."),
    },
    {
      id: "polite-verbs-3-m6",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: object("a1-value-ken", "a1-value-listen", "a1-value-obj-tv"),
      translation: L("Ken does not listen to television.", "Ken non ascolta la televisione."),
    },
    {
      id: "polite-verbs-3-m7",
      family: OBJECT,
      context: "a1-context-shop",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "omitted",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: object("a1-value-mina", "a1-value-buy", "a1-value-obj-water"),
      translation: L("Mina does not buy water.", "Mina non compra acqua."),
    },
    {
      id: "polite-verbs-3-m8",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: bare(WATASHI, "a1-value-return-bare"),
      translation: L("I do not return.", "Non torno."),
    },
  ],
  transfers: [
    {
      id: "polite-verbs-3-t1",
      family: BARE,
      context: "a1-context-workplace",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: bare(WATASHI, "a1-value-work-bare"),
      translation: L("I do not work.", "Non lavoro."),
    },
    {
      id: "polite-verbs-3-t2",
      family: BARE,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: bare("a1-value-yuki", "a1-value-study-bare"),
      translation: L("Yuki does not study.", "Yuki non studia."),
    },
    {
      id: "polite-verbs-3-t3",
      family: BARE,
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: bare("a1-value-ken", "a1-value-do-bare"),
      translation: L("Ken does not do it.", "Ken non lo fa."),
    },
    {
      id: "polite-verbs-3-t4",
      family: BARE,
      context: "a1-context-home",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: bare("a1-value-mina", "a1-value-rest-bare"),
      translation: L("Mina does not take a break.", "Mina non fa una pausa."),
    },
    {
      id: "polite-verbs-3-t5",
      family: OBJECT,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      form: { polarity: "negative", tense: "present", formality: "polite" },
      slots: object(WATASHI, "a1-value-eat", "a1-value-obj-bread"),
      translation: L("I do not eat bread.", "Non mangio pane."),
    },
  ],
});

const lesson4: A1BuiltLesson = buildA1InstructionalLesson({
  id: "polite-verbs-4",
  moduleId: MODULE_ID,
  order: 4,
  primaryCanDoId: "a1-can-do-polite-verbs",
  supportingCanDoIds: ["a1-can-do-topic-questions"],
  introducedConceptIds: [A1_CONCEPT_LOCATION_PARTICLE],
  introducedSenseIds: ["a1-sense-work", "a1-sense-return-location"],
  models: [
    {
      id: "polite-verbs-4-m1",
      family: LOCATION,
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-teacher",
      subjectRealization: "omitted",
      interrogative: true,
      speakerRole: "a1-role-learner",
      addresseeRole: "a1-role-teacher",
      slots: location("a1-value-anata", "a1-value-return-location", "a1-value-loc-doko"),
      translation: L("Where are you returning to?", "Dove stai tornando?"),
    },
    {
      id: "polite-verbs-4-m2",
      family: LOCATION,
      context: "a1-context-workplace",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      speakerRole: "a1-role-teacher",
      addresseeRole: "a1-role-learner",
      slots: location(WATASHI, "a1-value-work", "a1-value-loc-company"),
      translation: L("I work at the company.", "Lavoro in azienda."),
    },
    {
      id: "polite-verbs-4-m3",
      family: LOCATION,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: location("a1-value-yuki", "a1-value-work", "a1-value-loc-library"),
      translation: L("Yuki works at the library.", "Yuki lavora in biblioteca."),
    },
    {
      id: "polite-verbs-4-m4",
      family: LOCATION,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: location("a1-value-ken", "a1-value-work", "a1-value-loc-cafe"),
      translation: L("Ken works at the cafe.", "Ken lavora al bar."),
    },
    {
      id: "polite-verbs-4-m5",
      family: LOCATION,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: location("a1-value-mina", "a1-value-work", "a1-value-loc-school"),
      translation: L("Mina works at the school.", "Mina lavora a scuola."),
    },
    {
      id: "polite-verbs-4-m6",
      family: LOCATION,
      context: "a1-context-workplace",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      speakerRole: "a1-role-teacher",
      addresseeRole: "a1-role-learner",
      slots: location(WATASHI, "a1-value-return-location", "a1-value-loc-company"),
      translation: L("I am returning to the company.", "Torno in azienda."),
    },
    {
      id: "polite-verbs-4-m7",
      family: LOCATION,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: location("a1-value-yuki", "a1-value-return-location", "a1-value-loc-library"),
      translation: L("Yuki is returning to the library.", "Yuki torna in biblioteca."),
    },
    {
      id: "polite-verbs-4-m8",
      family: LOCATION,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: location("a1-value-ken", "a1-value-return-location", "a1-value-loc-cafe"),
      translation: L("Ken is returning to the cafe.", "Ken torna al bar."),
    },
  ],
  transfers: [
    {
      id: "polite-verbs-4-t1",
      family: LOCATION,
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: location("a1-value-mina", "a1-value-return-location", "a1-value-loc-school"),
      translation: L("Mina is returning to school.", "Mina torna a scuola."),
    },
    {
      id: "polite-verbs-4-t2",
      family: LOCATION,
      context: "a1-context-classroom",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: location(WATASHI, "a1-value-return-location", "a1-value-loc-library"),
      translation: L("I am returning to the library.", "Torno in biblioteca."),
    },
    {
      id: "polite-verbs-4-t3",
      family: LOCATION,
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: location("a1-value-yuki", "a1-value-work", "a1-value-loc-cafe"),
      translation: L("Yuki works at the cafe.", "Yuki lavora al bar."),
    },
    {
      id: "polite-verbs-4-t4",
      family: LOCATION,
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: location("a1-value-ken", "a1-value-return-location", "a1-value-loc-company"),
      translation: L("Ken is returning to the company.", "Ken torna in azienda."),
    },
    {
      id: "polite-verbs-4-t5",
      family: LOCATION,
      context: "a1-context-cafe",
      subjectReferent: SELF,
      subjectRealization: "omitted",
      slots: location(WATASHI, "a1-value-work", "a1-value-loc-cafe"),
      translation: L("I work at the cafe.", "Lavoro al bar."),
    },
  ],
});

export const modulePoliteVerbsLessons: readonly A1BuiltLesson[] = [
  lesson1,
  lesson2,
  lesson3,
  lesson4,
];

export const modulePoliteVerbsRecipe: A1ModuleRecipe = defineA1Module({
  id: MODULE_ID,
  order: 4,
  prerequisiteIds: ["topic-questions"],
  lessonIds: modulePoliteVerbsLessons.map(({ recipe }) => recipe.id),
  outcomeCopyId: "a1-module-outcome-polite-verbs",
});

/** Staged only; Task 5 owns promotion into the release recurrence timeline. */
export const modulePoliteVerbsVerbUseRecords: readonly VerbUseRecord[] = [
  a1VerbUseRecord({
    senseId: "a1-sense-work-bare",
    introductionLessonId: "polite-verbs-1",
    introductionVariantIds: ["polite-verbs-1-m1", "polite-verbs-1-m5"],
    exerciseRoundId: "polite-verbs-1-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-1-m1",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-study-bare",
    introductionLessonId: "polite-verbs-1",
    introductionVariantIds: ["polite-verbs-1-m2", "polite-verbs-1-m6"],
    exerciseRoundId: "polite-verbs-1-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-1-m2",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-do-bare",
    introductionLessonId: "polite-verbs-1",
    introductionVariantIds: ["polite-verbs-1-m3", "polite-verbs-1-m7"],
    exerciseRoundId: "polite-verbs-1-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-1-m3",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-rest-bare",
    introductionLessonId: "polite-verbs-1",
    introductionVariantIds: ["polite-verbs-1-m4", "polite-verbs-1-m8"],
    exerciseRoundId: "polite-verbs-1-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-1-m4",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-eat",
    introductionLessonId: "polite-verbs-2",
    introductionVariantIds: ["polite-verbs-2-m1", "polite-verbs-2-m5"],
    exerciseRoundId: "polite-verbs-2-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-2-m1",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-drink",
    introductionLessonId: "polite-verbs-2",
    introductionVariantIds: ["polite-verbs-2-m2", "polite-verbs-2-m6"],
    exerciseRoundId: "polite-verbs-2-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-2-m2",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-read",
    introductionLessonId: "polite-verbs-2",
    introductionVariantIds: ["polite-verbs-2-m3", "polite-verbs-2-m7"],
    exerciseRoundId: "polite-verbs-2-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-2-m3",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-write",
    introductionLessonId: "polite-verbs-2",
    introductionVariantIds: ["polite-verbs-2-m4", "polite-verbs-2-m8"],
    exerciseRoundId: "polite-verbs-2-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-2-m4",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-see",
    introductionLessonId: "polite-verbs-3",
    introductionVariantIds: ["polite-verbs-3-m1", "polite-verbs-3-m5"],
    exerciseRoundId: "polite-verbs-3-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-3-m1",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-listen",
    introductionLessonId: "polite-verbs-3",
    introductionVariantIds: ["polite-verbs-3-m2", "polite-verbs-3-m6"],
    exerciseRoundId: "polite-verbs-3-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-3-m2",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-buy",
    introductionLessonId: "polite-verbs-3",
    introductionVariantIds: ["polite-verbs-3-m3", "polite-verbs-3-m7"],
    exerciseRoundId: "polite-verbs-3-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-3-m3",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-return-bare",
    introductionLessonId: "polite-verbs-3",
    introductionVariantIds: ["polite-verbs-3-m4", "polite-verbs-3-m8"],
    exerciseRoundId: "polite-verbs-3-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-3-m4",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-work",
    introductionLessonId: "polite-verbs-4",
    introductionVariantIds: ["polite-verbs-4-m2", "polite-verbs-4-m3"],
    exerciseRoundId: "polite-verbs-4-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-4-m2",
  }),
  a1VerbUseRecord({
    senseId: "a1-sense-return-location",
    introductionLessonId: "polite-verbs-4",
    introductionVariantIds: ["polite-verbs-4-m1", "polite-verbs-4-m6"],
    exerciseRoundId: "polite-verbs-4-round-1",
    exerciseKind: "tile-ordering",
    exerciseTargetVariantId: "polite-verbs-4-m1",
  }),
];
