/**
 * Staged Foundations module 2 — topics, focus, and identity questions.
 *
 * These recipes remain outside the published A1 catalog until Task 5 promotes
 * the entire expanded Foundations sequence.
 */

import { defineA1Module } from "../authoring";
import type { A1ModuleRecipe } from "../types";
import type { VerbUseRecord } from "../../foundations/types";
import {
  A1_CONCEPT_INTERROGATIVE_KA,
  A1_CONCEPT_NOMINATIVE_GA,
  buildA1InstructionalLesson,
  type A1BuiltLesson,
  type A1LineSpec,
  type Bilingual,
} from "./shared";

const MODULE_ID = "topic-questions";
const L = (en: string, it: string): Bilingual => ({ en, it });

const cop = (subject: string, object: string) => ({
  subject,
  predicate: "a1-value-be",
  object,
});

const question = (spec: Omit<A1LineSpec, "interrogative">): A1LineSpec => ({
  ...spec,
  interrogative: true,
});

const lesson1: A1BuiltLesson = buildA1InstructionalLesson({
  id: "topic-questions-1",
  moduleId: MODULE_ID,
  order: 1,
  primaryCanDoId: "a1-can-do-topic-questions",
  supportingCanDoIds: ["a1-can-do-sentence-foundations"],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [],
  introducedSenseIds: [],
  models: [
    {
      id: "topic-questions-1-m1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-japanese-person"),
      translation: L("Yuki is Japanese.", "Yuki è giapponese."),
    },
    {
      id: "topic-questions-1-m2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: cop("a1-value-ken", "a1-value-obj-italian-person"),
      translation: L("Ken is Italian.", "Ken è italiano."),
    },
    {
      id: "topic-questions-1-m3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-american-person"),
      translation: L("Mina is American.", "Mina è americana."),
    },
    {
      id: "topic-questions-1-m4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-friend",
      subjectRealization: "explicit",
      slots: cop("a1-value-friend-subject", "a1-value-obj-french-person"),
      translation: L("The friend is French.", "L'amico è francese."),
    },
    {
      id: "topic-questions-1-m5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: cop("a1-value-yuki", "a1-value-obj-japanese-person"),
      translation: L("Yuki is Japanese.", "Yuki è giapponese."),
    },
    {
      id: "topic-questions-1-m6",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      slots: cop("a1-value-ken", "a1-value-obj-italian-person"),
      translation: L("Ken is Italian.", "Ken è italiano."),
    },
    {
      id: "topic-questions-1-m7",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "omitted",
      slots: cop("a1-value-mina", "a1-value-obj-american-person"),
      translation: L("Mina is American.", "Mina è americana."),
    },
    {
      id: "topic-questions-1-m8",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-friend",
      subjectRealization: "omitted",
      slots: cop("a1-value-friend-subject", "a1-value-obj-french-person"),
      translation: L("The friend is French.", "L'amico è francese."),
    },
  ],
  transfers: [
    {
      id: "topic-questions-1-t1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-french-person"),
      translation: L("Yuki is French.", "Yuki è francese."),
    },
    {
      id: "topic-questions-1-t2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "omitted",
      slots: cop("a1-value-ken", "a1-value-obj-japanese-person"),
      translation: L("Ken is Japanese.", "Ken è giapponese."),
    },
    {
      id: "topic-questions-1-t3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-italian-person"),
      translation: L("Mina is Italian.", "Mina è italiana."),
    },
    {
      id: "topic-questions-1-t4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-friend",
      subjectRealization: "omitted",
      slots: cop("a1-value-friend-subject", "a1-value-obj-american-person"),
      translation: L("The friend is American.", "L'amico è americano."),
    },
    {
      id: "topic-questions-1-t5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "omitted",
      slots: cop("a1-value-yuki", "a1-value-obj-japanese-person"),
      translation: L("Yuki is Japanese.", "Yuki è giapponese."),
    },
  ],
});

const lesson2: A1BuiltLesson = buildA1InstructionalLesson({
  id: "topic-questions-2",
  moduleId: MODULE_ID,
  order: 2,
  primaryCanDoId: "a1-can-do-topic-questions",
  supportingCanDoIds: ["a1-can-do-sentence-foundations"],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [A1_CONCEPT_NOMINATIVE_GA],
  introducedSenseIds: [],
  models: [
    {
      id: "topic-questions-2-m1",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-japanese-person"),
      translation: L("Yuki is Japanese.", "Yuki è giapponese."),
    },
    {
      id: "topic-questions-2-m2",
      family: "a1-family-focus-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-japanese-person"),
      translation: L("Yuki is the one who is Japanese.", "Yuki è quella giapponese."),
    },
    {
      id: "topic-questions-2-m3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: cop("a1-value-ken", "a1-value-obj-italian-person"),
      translation: L("Ken is Italian.", "Ken è italiano."),
    },
    {
      id: "topic-questions-2-m4",
      family: "a1-family-focus-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-ken",
      subjectRealization: "explicit",
      slots: cop("a1-value-ken", "a1-value-obj-italian-person"),
      translation: L("Ken is the one who is Italian.", "Ken è quello italiano."),
    },
    {
      id: "topic-questions-2-m5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-japanese"),
      translation: L("It is Japanese.", "È giapponese."),
    },
    {
      id: "topic-questions-2-m6",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-english"),
      translation: L("It is English.", "È inglese."),
    },
    {
      id: "topic-questions-2-m7",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-italian"),
      translation: L("It is Italian.", "È italiano."),
    },
    {
      id: "topic-questions-2-m8",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-french-language"),
      translation: L("It is French.", "È francese."),
    },
  ],
  transfers: [
    {
      id: "topic-questions-2-t1",
      family: "a1-family-focus-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-american-person"),
      translation: L("Mina is the one who is American.", "Mina è quella americana."),
    },
    {
      id: "topic-questions-2-t2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-mina",
      subjectRealization: "explicit",
      slots: cop("a1-value-mina", "a1-value-obj-american-person"),
      translation: L("Mina is American.", "Mina è americana."),
    },
    {
      id: "topic-questions-2-t3",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-french-language"),
      translation: L("It is French.", "È francese."),
    },
    {
      id: "topic-questions-2-t4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-obj-japanese"),
      translation: L("It is Japanese.", "È giapponese."),
    },
    {
      id: "topic-questions-2-t5",
      family: "a1-family-focus-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-yuki",
      subjectRealization: "explicit",
      slots: cop("a1-value-yuki", "a1-value-obj-japanese-person"),
      translation: L("Yuki is the one who is Japanese.", "Yuki è quella giapponese."),
    },
  ],
});

const lesson3: A1BuiltLesson = buildA1InstructionalLesson({
  id: "topic-questions-3",
  moduleId: MODULE_ID,
  order: 3,
  primaryCanDoId: "a1-can-do-topic-questions",
  supportingCanDoIds: ["a1-can-do-sentence-foundations"],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [A1_CONCEPT_INTERROGATIVE_KA],
  introducedSenseIds: [],
  models: [
    question({
      id: "topic-questions-3-m1",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-student-subject", "a1-value-q-dare"),
      translation: L("Who is the student?", "Chi è lo studente?"),
    }),
    question({
      id: "topic-questions-3-m2",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-name-subject", "a1-value-q-nan"),
      translation: L("What is the name?", "Qual è il nome?"),
    }),
    question({
      id: "topic-questions-3-m3",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-q-nan"),
      translation: L("What is it?", "Che cos'è?"),
    }),
    question({
      id: "topic-questions-3-m4",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-station",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-student-subject", "a1-value-q-doko"),
      translation: L("Where is the student?", "Dov'è lo studente?"),
    }),
    question({
      id: "topic-questions-3-m5",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-teacher",
      subjectRealization: "explicit",
      slots: cop("a1-value-teacher-subject", "a1-value-q-dare"),
      translation: L("Who is the teacher?", "Chi è l'insegnante?"),
    }),
    question({
      id: "topic-questions-3-m6",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-q-nani"),
      translation: L(
        "What exactly is this?",
        "Che cos'è esattamente questo?",
      ),
    }),
    question({
      id: "topic-questions-3-m7",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-station",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-q-doko"),
      translation: L("Where is it?", "Dov'è?"),
    }),
    question({
      id: "topic-questions-3-m8",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-friend",
      subjectRealization: "explicit",
      slots: cop("a1-value-friend-subject", "a1-value-q-dare"),
      translation: L("Who is the friend?", "Chi è l'amico?"),
    }),
  ],
  transfers: [
    question({
      id: "topic-questions-3-t1",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-teacher",
      subjectRealization: "explicit",
      slots: cop("a1-value-teacher-subject", "a1-value-q-doko"),
      translation: L("Where is the teacher?", "Dov'è l'insegnante?"),
    }),
    question({
      id: "topic-questions-3-t2",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-person",
      subjectRealization: "explicit",
      slots: cop("a1-value-student-subject", "a1-value-q-dare"),
      translation: L("Who is the student?", "Chi è lo studente?"),
    }),
    question({
      id: "topic-questions-3-t3",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-classroom",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "omitted",
      slots: cop("a1-value-kore", "a1-value-q-nan"),
      translation: L("What is it?", "Che cos'è?"),
    }),
    question({
      id: "topic-questions-3-t4",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-station",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-name-subject", "a1-value-q-nan"),
      translation: L("What is the name?", "Qual è il nome?"),
    }),
    question({
      id: "topic-questions-3-t5",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-first-meeting",
      subjectReferent: "a1-referent-friend",
      subjectRealization: "explicit",
      slots: cop("a1-value-friend-subject", "a1-value-q-doko"),
      translation: L("Where is the friend?", "Dov'è l'amico?"),
    }),
  ],
});

const lesson4: A1BuiltLesson = buildA1InstructionalLesson({
  id: "topic-questions-4",
  moduleId: MODULE_ID,
  order: 4,
  primaryCanDoId: "a1-can-do-topic-questions",
  supportingCanDoIds: ["a1-can-do-sentence-foundations"],
  diversityOverride: { minPredicates: 1 },
  introducedConceptIds: [],
  introducedSenseIds: [],
  models: [
    question({
      id: "topic-questions-4-m1",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-shop",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-kore", "a1-value-obj-bread"),
      translation: L("Is this bread?", "Questo è pane?"),
    }),
    {
      id: "topic-questions-4-m2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-shop",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-sore", "a1-value-obj-bread"),
      translation: L("That is bread.", "Quello è pane."),
    },
    question({
      id: "topic-questions-4-m3",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-shop",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-are", "a1-value-obj-bread"),
      translation: L("Is that over there bread?", "Quello laggiù è pane?"),
    }),
    question({
      id: "topic-questions-4-m4",
      family: "a1-family-focus-copular",
      context: "a1-context-shop",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-dore", "a1-value-obj-bread"),
      translation: L("Which one is bread?", "Quale è il pane?"),
    }),
    {
      id: "topic-questions-4-m5",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-kore", "a1-value-obj-bread"),
      translation: L("This is bread.", "Questo è pane."),
    },
    question({
      id: "topic-questions-4-m6",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-sore", "a1-value-obj-bread"),
      translation: L("Is that bread?", "Quello è pane?"),
    }),
    {
      id: "topic-questions-4-m7",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-shop",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-are", "a1-value-obj-bread"),
      translation: L("That over there is bread.", "Quello laggiù è pane."),
    },
    question({
      id: "topic-questions-4-m8",
      family: "a1-family-focus-copular",
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-dore", "a1-value-obj-bread"),
      translation: L("Which one is bread?", "Quale è il pane?"),
    }),
  ],
  transfers: [
    question({
      id: "topic-questions-4-t1",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-kore", "a1-value-obj-bread"),
      translation: L("Is this bread?", "Questo è pane?"),
    }),
    {
      id: "topic-questions-4-t2",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-sore", "a1-value-obj-bread"),
      translation: L("That is bread.", "Quello è pane."),
    },
    question({
      id: "topic-questions-4-t3",
      family: "a1-family-focus-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-dore", "a1-value-obj-bread"),
      translation: L("Which one is bread?", "Quale è il pane?"),
    }),
    {
      id: "topic-questions-4-t4",
      family: "a1-family-foundation-topic-copular",
      context: "a1-context-cafe",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-are", "a1-value-obj-bread"),
      translation: L("That over there is bread.", "Quello laggiù è pane."),
    },
    question({
      id: "topic-questions-4-t5",
      family: "a1-family-foundation-question-copular",
      context: "a1-context-workplace",
      subjectReferent: "a1-referent-thing",
      subjectRealization: "explicit",
      slots: cop("a1-value-sore", "a1-value-obj-bread"),
      translation: L("Is that bread?", "Quello è pane?"),
    }),
  ],
});

export const moduleTopicQuestionsLessons: readonly A1BuiltLesson[] = [
  lesson1,
  lesson2,
  lesson3,
  lesson4,
];

export const moduleTopicQuestionsRecipe: A1ModuleRecipe = defineA1Module({
  id: MODULE_ID,
  order: 3,
  prerequisiteIds: ["sentence-foundations"],
  lessonIds: moduleTopicQuestionsLessons.map(({ recipe }) => recipe.id),
  outcomeCopyId: "a1-module-outcome-topic-questions",
});

export const moduleTopicQuestionsVerbUseRecords: readonly VerbUseRecord[] =
  Object.freeze([]);
