import type { AssembledToken } from "../../../romaji/types";
import { deepFreeze } from "../../foundations/deepFreeze";
import { immutableReadonlyMap } from "../../foundations/immutableReadonlyMap";
import type { BaseLexeme, BaseVerbLexeme } from "./types";

const DYNAMIC_TE_CONSTRUCTIONS: readonly BaseVerbLexeme["allowedTeConstructions"][number][] =
  deepFreeze(["te", "request", "sequence", "te-imasu"]);
const EXISTENTIAL_TE_CONSTRUCTIONS: readonly BaseVerbLexeme["allowedTeConstructions"][number][] =
  deepFreeze(["te", "sequence"]);

function dictionaryToken(
  id: string,
  kana: string,
  romaji: string,
): readonly AssembledToken[] {
  return deepFreeze([
    {
      id: `${id}-dictionary`,
      jp: kana,
      romaji,
      kind: "lexical",
      boundaryBefore: "attach",
      source: { domain: "catalog", referenceId: id },
    },
  ]);
}

function verb(
  id: string,
  kana: string,
  romaji: string,
  verbClass: BaseVerbLexeme["verbClass"],
  aspect: BaseVerbLexeme["aspect"],
  firstTeachLessonId: string,
  allowedTeConstructions: BaseVerbLexeme["allowedTeConstructions"],
): BaseVerbLexeme {
  return {
    id,
    kana,
    romaji,
    meaningCopyId: `${id}-meaning`,
    firstTeachLessonId,
    countable: true,
    category: "verb",
    verbClass,
    aspect,
    allowedTeConstructions,
    dictionaryTokens: dictionaryToken(id, kana, romaji),
  };
}

function noun(
  id: string,
  kana: string,
  romaji: string,
  firstTeachLessonId: string,
): BaseLexeme {
  return {
    id,
    kana,
    romaji,
    meaningCopyId: `${id}-meaning`,
    firstTeachLessonId,
    countable: true,
    category: "noun",
  };
}

export const BASE_LEXICON: readonly BaseLexeme[] = deepFreeze([
  verb("verb-kaku", "かく", "kaku", "godan", "dynamic", "polite-verbs-1", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-yomu", "よむ", "yomu", "godan", "dynamic", "polite-verbs-1", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-nomu", "のむ", "nomu", "godan", "dynamic", "polite-verbs-1", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-kau", "かう", "kau", "godan", "dynamic", "polite-verbs-1", DYNAMIC_TE_CONSTRUCTIONS),
  verb(
    "verb-hataraku",
    "はたらく",
    "hataraku",
    "godan",
    "dynamic",
    "polite-verbs-1",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb("verb-asobu", "あそぶ", "asobu", "godan", "dynamic", "polite-verbs-1", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-oyogu", "およぐ", "oyogu", "godan", "dynamic", "polite-verbs-2", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-taberu", "たべる", "taberu", "ichidan", "dynamic", "polite-verbs-2", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-miru", "みる", "miru", "ichidan", "dynamic", "polite-verbs-2", DYNAMIC_TE_CONSTRUCTIONS),
  verb(
    "verb-kaeru",
    "かえる",
    "kaeru",
    "godan",
    "dynamic",
    "polite-verbs-2",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb("verb-suru", "する", "suru", "suru", "dynamic", "polite-verbs-2", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-kuru", "くる", "kuru", "kuru", "dynamic", "polite-verbs-2", DYNAMIC_TE_CONSTRUCTIONS),
  verb(
    "verb-benkyou-suru",
    "べんきょうする",
    "benkyou suru",
    "suru",
    "dynamic",
    "polite-verbs-3",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb(
    "verb-denwa-suru",
    "でんわする",
    "denwa suru",
    "suru",
    "dynamic",
    "polite-verbs-3",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb(
    "verb-sanpo-suru",
    "さんぽする",
    "sanpo suru",
    "suru",
    "dynamic",
    "polite-verbs-3",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb(
    "verb-motte-kuru",
    "もってくる",
    "motte kuru",
    "kuru",
    "dynamic",
    "requests-connection-1",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  {
    ...verb(
      "verb-iku",
      "いく",
      "iku",
      "godan",
      "dynamic",
      "polite-verbs-4",
      DYNAMIC_TE_CONSTRUCTIONS,
    ),
    teFormException: {
      stemKana: "い",
      stemRomaji: "i",
      endingKana: "って",
      endingRomaji: "tte",
    },
  },
  verb("verb-yasumu", "やすむ", "yasumu", "godan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-okiru", "おきる", "okiru", "ichidan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-neru", "ねる", "neru", "ichidan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-aruku", "あるく", "aruku", "godan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-kiku", "きく", "kiku", "godan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-tsukuru", "つくる", "tsukuru", "godan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-au", "あう", "au", "godan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-utau", "うたう", "utau", "godan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-hanasu", "はなす", "hanasu", "godan", "dynamic", "polite-verbs-4", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-matsu", "まつ", "matsu", "godan", "dynamic", "polite-verbs-3", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-shinu", "しぬ", "shinu", "godan", "dynamic", "requests-connection-1", DYNAMIC_TE_CONSTRUCTIONS),
  verb("verb-hashiru", "はしる", "hashiru", "godan", "dynamic", "time-movement-1", DYNAMIC_TE_CONSTRUCTIONS),
  verb(
    "verb-ryokou-suru",
    "りょこうする",
    "ryokou suru",
    "suru",
    "dynamic",
    "time-movement-1",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb(
    "verb-ryouri-suru",
    "りょうりする",
    "ryouri suru",
    "suru",
    "dynamic",
    "time-movement-1",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb(
    "verb-dekakeru",
    "でかける",
    "dekakeru",
    "ichidan",
    "dynamic",
    "time-movement-1",
    DYNAMIC_TE_CONSTRUCTIONS,
  ),
  verb(
    "verb-aru",
    "ある",
    "aru",
    "godan",
    "stative",
    "existence-location-1",
    EXISTENTIAL_TE_CONSTRUCTIONS,
  ),
  verb(
    "verb-iru",
    "いる",
    "iru",
    "ichidan",
    "stative",
    "existence-location-1",
    EXISTENTIAL_TE_CONSTRUCTIONS,
  ),
  {
    id: "adjective-takai",
    kana: "たかい",
    romaji: "takai",
    meaningCopyId: "adjective-takai-meaning",
    firstTeachLessonId: "copula-adjectives-3",
    countable: true,
    category: "adjective",
    adjectiveClass: "i",
  },
  {
    id: "adjective-oishii",
    kana: "おいしい",
    romaji: "oishii",
    meaningCopyId: "adjective-oishii-meaning",
    firstTeachLessonId: "copula-adjectives-3",
    countable: true,
    category: "adjective",
    adjectiveClass: "i",
  },
  {
    id: "adjective-ii",
    kana: "いい",
    romaji: "ii",
    meaningCopyId: "adjective-ii-meaning",
    firstTeachLessonId: "copula-adjectives-3",
    countable: true,
    category: "adjective",
    adjectiveClass: "i",
    iAdjectiveInflection: {
      negativeStemKana: "よ",
      negativeStemRomaji: "yo",
    },
  },
  {
    id: "adjective-shizuka",
    kana: "しずか",
    romaji: "shizuka",
    meaningCopyId: "adjective-shizuka-meaning",
    firstTeachLessonId: "copula-adjectives-4",
    countable: true,
    category: "adjective",
    adjectiveClass: "na",
  },
  {
    id: "adjective-kirei",
    kana: "きれい",
    romaji: "kirei",
    meaningCopyId: "adjective-kirei-meaning",
    firstTeachLessonId: "copula-adjectives-4",
    countable: true,
    category: "adjective",
    adjectiveClass: "na",
  },
  {
    id: "adjective-yuumei",
    kana: "ゆうめい",
    romaji: "yuumei",
    meaningCopyId: "adjective-yuumei-meaning",
    firstTeachLessonId: "copula-adjectives-4",
    countable: true,
    category: "adjective",
    adjectiveClass: "na",
  },
  {
    id: "adjective-kirai",
    kana: "きらい",
    romaji: "kirai",
    meaningCopyId: "adjective-kirai-meaning",
    firstTeachLessonId: "copula-adjectives-4",
    countable: true,
    category: "adjective",
    adjectiveClass: "na",
  },
  {
    id: "noun-gakusei",
    kana: "がくせい",
    romaji: "gakusei",
    meaningCopyId: "noun-gakusei-meaning",
    firstTeachLessonId: "sentence-foundations-1",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-sensei",
    kana: "せんせい",
    romaji: "sensei",
    meaningCopyId: "noun-sensei-meaning",
    firstTeachLessonId: "sentence-foundations-1",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-watashi",
    kana: "わたし",
    romaji: "watashi",
    meaningCopyId: "noun-watashi-meaning",
    firstTeachLessonId: "sentence-foundations-1",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-tanaka",
    kana: "たなかさん",
    romaji: "Tanaka-san",
    meaningCopyId: "noun-tanaka-meaning",
    firstTeachLessonId: "sentence-foundations-2",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-yamada",
    kana: "やまださん",
    romaji: "Yamada-san",
    meaningCopyId: "noun-yamada-meaning",
    firstTeachLessonId: "sentence-foundations-2",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-hito",
    kana: "ひと",
    romaji: "hito",
    meaningCopyId: "noun-hito-meaning",
    firstTeachLessonId: "sentence-foundations-2",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-kangoshi",
    kana: "かんごし",
    romaji: "kangoshi",
    meaningCopyId: "noun-kangoshi-meaning",
    firstTeachLessonId: "sentence-foundations-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-bengoshi",
    kana: "べんごし",
    romaji: "bengoshi",
    meaningCopyId: "noun-bengoshi-meaning",
    firstTeachLessonId: "sentence-foundations-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-tomodachi",
    kana: "ともだち",
    romaji: "tomodachi",
    meaningCopyId: "noun-tomodachi-meaning",
    firstTeachLessonId: "sentence-foundations-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-isha",
    kana: "いしゃ",
    romaji: "isha",
    meaningCopyId: "noun-isha-meaning",
    firstTeachLessonId: "sentence-foundations-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-daigakusei",
    kana: "だいがくせい",
    romaji: "daigakusei",
    meaningCopyId: "noun-daigakusei-meaning",
    firstTeachLessonId: "sentence-foundations-4",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-ryuugakusei",
    kana: "りゅうがくせい",
    romaji: "ryuugakusei",
    meaningCopyId: "noun-ryuugakusei-meaning",
    firstTeachLessonId: "sentence-foundations-4",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-kazoku",
    kana: "かぞく",
    romaji: "kazoku",
    meaningCopyId: "noun-kazoku-meaning",
    firstTeachLessonId: "sentence-foundations-1",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-tokyo",
    kana: "とうきょう",
    romaji: "Toukyou",
    meaningCopyId: "noun-tokyo-meaning",
    firstTeachLessonId: "topic-questions-1",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-kyoto",
    kana: "きょうと",
    romaji: "Kyouto",
    meaningCopyId: "noun-kyoto-meaning",
    firstTeachLessonId: "topic-questions-1",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-osaka",
    kana: "おおさか",
    romaji: "Oosaka",
    meaningCopyId: "noun-osaka-meaning",
    firstTeachLessonId: "topic-questions-1",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-toshi",
    kana: "とし",
    romaji: "toshi",
    meaningCopyId: "noun-toshi-meaning",
    firstTeachLessonId: "topic-questions-1",
    countable: true,
    category: "noun",
  },
  {
    id: "name-sakura",
    kana: "さくら",
    romaji: "Sakura",
    meaningCopyId: "name-sakura-meaning",
    firstTeachLessonId: "sentence-foundations-1",
    countable: true,
    category: "noun",
  },
  {
    id: "name-ken",
    kana: "けん",
    romaji: "Ken",
    meaningCopyId: "name-ken-meaning",
    firstTeachLessonId: "sentence-foundations-1",
    countable: true,
    category: "noun",
  },
  {
    id: "name-mika",
    kana: "みか",
    romaji: "Mika",
    meaningCopyId: "name-mika-meaning",
    firstTeachLessonId: "sentence-foundations-4",
    countable: true,
    category: "noun",
  },
  {
    id: "name-sora",
    kana: "そら",
    romaji: "Sora",
    meaningCopyId: "name-sora-meaning",
    firstTeachLessonId: "sentence-foundations-4",
    countable: true,
    category: "noun",
  },
  {
    id: "name-haru",
    kana: "はる",
    romaji: "Haru",
    meaningCopyId: "name-haru-meaning",
    firstTeachLessonId: "sentence-foundations-4",
    countable: true,
    category: "noun",
  },
  {
    id: "name-ai",
    kana: "あい",
    romaji: "Ai",
    meaningCopyId: "name-ai-meaning",
    firstTeachLessonId: "sentence-foundations-4",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-satou",
    kana: "さとうさん",
    romaji: "Satou-san",
    meaningCopyId: "noun-satou-meaning",
    firstTeachLessonId: "topic-questions-2",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-suzuki",
    kana: "すずきさん",
    romaji: "Suzuki-san",
    meaningCopyId: "noun-suzuki-meaning",
    firstTeachLessonId: "topic-questions-2",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-mari",
    kana: "まりさん",
    romaji: "Mari-san",
    meaningCopyId: "noun-mari-meaning",
    firstTeachLessonId: "topic-questions-2",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-chichi",
    kana: "ちち",
    romaji: "chichi",
    meaningCopyId: "noun-chichi-meaning",
    firstTeachLessonId: "topic-questions-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-haha",
    kana: "はは",
    romaji: "haha",
    meaningCopyId: "noun-haha-meaning",
    firstTeachLessonId: "topic-questions-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-otousan",
    kana: "おとうさん",
    romaji: "otousan",
    meaningCopyId: "noun-otousan-meaning",
    firstTeachLessonId: "topic-questions-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-okaasan",
    kana: "おかあさん",
    romaji: "okaasan",
    meaningCopyId: "noun-okaasan-meaning",
    firstTeachLessonId: "topic-questions-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-namae",
    kana: "なまえ",
    romaji: "namae",
    meaningCopyId: "noun-namae-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-kuni",
    kana: "くに",
    romaji: "kuni",
    meaningCopyId: "noun-kuni-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-nihon",
    kana: "にほん",
    romaji: "nihon",
    meaningCopyId: "noun-nihon-meaning",
    firstTeachLessonId: "topic-questions-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-chuugoku",
    kana: "ちゅうごく",
    romaji: "chuugoku",
    meaningCopyId: "noun-chuugoku-meaning",
    firstTeachLessonId: "topic-questions-3",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-dare",
    kana: "だれ",
    romaji: "dare",
    meaningCopyId: "noun-dare-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-nan",
    kana: "なん",
    romaji: "nan",
    meaningCopyId: "noun-nan-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "noun",
  },
  {
    id: "expression-hai",
    kana: "はい",
    romaji: "hai",
    meaningCopyId: "expression-hai-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "expression",
  },
  {
    id: "expression-iie",
    kana: "いいえ",
    romaji: "iie",
    meaningCopyId: "expression-iie-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "expression",
  },
  {
    id: "expression-sou",
    kana: "そう",
    romaji: "sou",
    meaningCopyId: "expression-sou-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "expression",
  },
  {
    id: "noun-yuki",
    kana: "ゆき",
    romaji: "Yuki",
    meaningCopyId: "noun-yuki-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "noun",
  },
  {
    id: "noun-yuki-san",
    kana: "ゆきさん",
    romaji: "Yuki-san",
    meaningCopyId: "noun-yuki-san-meaning",
    firstTeachLessonId: "topic-questions-4",
    countable: true,
    category: "noun",
  },
  noun("noun-gohan", "ごはん", "gohan", "argument-particles-1"),
  noun("noun-mizu", "みず", "mizu", "argument-particles-1"),
  noun("noun-tegami", "てがみ", "tegami", "argument-particles-1"),
  noun("noun-kudamono", "くだもの", "kudamono", "argument-particles-1"),
  noun("noun-zasshi", "ざっし", "zasshi", "argument-particles-1"),
  noun("noun-eki", "えき", "eki", "argument-particles-2"),
  noun("noun-daigaku", "だいがく", "daigaku", "argument-particles-2"),
  noun("noun-byouin", "びょういん", "byouin", "argument-particles-2"),
  noun("noun-mise", "みせ", "mise", "argument-particles-2"),
  noun("noun-toshokan", "としょかん", "toshokan", "argument-particles-3"),
  noun("noun-kouen", "こうえん", "kouen", "argument-particles-3"),
  noun("noun-densha", "でんしゃ", "densha", "argument-particles-3"),
  noun("noun-jitensha", "じてんしゃ", "jitensha", "argument-particles-3"),
  noun("noun-enpitsu", "えんぴつ", "enpitsu", "argument-particles-3"),
  noun("noun-shokudou", "しょくどう", "shokudou", "argument-particles-4"),
  noun("noun-jimusho", "じむしょ", "jimusho", "argument-particles-4"),
  noun("noun-kasa", "かさ", "kasa", "argument-particles-4"),
  noun("noun-nikki", "にっき", "nikki", "argument-particles-4"),
  noun("noun-kyou", "きょう", "kyou", "time-movement-2"),
  noun("noun-ashita", "あした", "ashita", "time-movement-2"),
  noun("noun-getsuyoubi", "げつようび", "getsuyoubi", "time-movement-2"),
  noun("noun-shichiji", "しちじ", "shichiji", "time-movement-2"),
  noun("noun-kuji", "くじ", "kuji", "time-movement-2"),
  noun("noun-goji", "ごじ", "goji", "time-movement-2"),
  noun("noun-kinou", "きのう", "kinou", "time-movement-3"),
  noun("noun-senshuu", "せんしゅう", "senshuu", "time-movement-3"),
  noun("noun-konshuu", "こんしゅう", "konshuu", "time-movement-3"),
  noun("noun-raishuu", "らいしゅう", "raishuu", "time-movement-3"),
  noun("noun-kaigi", "かいぎ", "kaigi", "time-movement-4"),
  noun("noun-shigoto", "しごと", "shigoto", "time-movement-4"),
  noun("noun-yotei", "よてい", "yotei", "time-movement-4"),
  noun("noun-hirugohan", "ひるごはん", "hirugohan", "time-movement-4"),
  noun("noun-ban", "ばん", "ban", "time-movement-4"),
  noun("noun-kesa", "けさ", "kesa", "time-movement-4"),
  noun("noun-konban", "こんばん", "konban", "time-movement-4"),
  noun("noun-nichiyoubi", "にちようび", "nichiyoubi", "time-movement-4"),
  {
    id: "anchor-asa",
    kana: "あさ",
    romaji: "asa",
    meaningCopyId: "anchor-asa-meaning",
    firstTeachLessonId: "sounds-1",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-ie",
    kana: "いえ",
    romaji: "ie",
    meaningCopyId: "anchor-ie-meaning",
    firstTeachLessonId: "sounds-1",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-umi",
    kana: "うみ",
    romaji: "umi",
    meaningCopyId: "anchor-umi-meaning",
    firstTeachLessonId: "sounds-1",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-neko",
    kana: "ねこ",
    romaji: "neko",
    meaningCopyId: "anchor-neko-meaning",
    firstTeachLessonId: "sounds-1",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-kagi",
    kana: "かぎ",
    romaji: "kagi",
    meaningCopyId: "anchor-kagi-meaning",
    firstTeachLessonId: "sounds-2",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-kaze",
    kana: "かぜ",
    romaji: "kaze",
    meaningCopyId: "anchor-kaze-meaning",
    firstTeachLessonId: "sounds-2",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-denwa",
    kana: "でんわ",
    romaji: "denwa",
    meaningCopyId: "anchor-denwa-meaning",
    firstTeachLessonId: "sounds-2",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-pan",
    kana: "ぱん",
    romaji: "pan",
    meaningCopyId: "anchor-pan-meaning",
    firstTeachLessonId: "sounds-2",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-obaasan",
    kana: "おばあさん",
    romaji: "obaasan",
    meaningCopyId: "anchor-obaasan-meaning",
    firstTeachLessonId: "sounds-3",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-gakkou",
    kana: "がっこう",
    romaji: "gakkou",
    meaningCopyId: "anchor-gakkou-meaning",
    firstTeachLessonId: "sounds-3",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-hon",
    kana: "ほん",
    romaji: "hon",
    meaningCopyId: "anchor-hon-meaning",
    firstTeachLessonId: "sounds-3",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-kippu",
    kana: "きっぷ",
    romaji: "kippu",
    meaningCopyId: "anchor-kippu-meaning",
    firstTeachLessonId: "sounds-3",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-kyaku",
    kana: "きゃく",
    romaji: "kyaku",
    meaningCopyId: "anchor-kyaku-meaning",
    firstTeachLessonId: "sounds-4",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-shashin",
    kana: "しゃしん",
    romaji: "shashin",
    meaningCopyId: "anchor-shashin-meaning",
    firstTeachLessonId: "sounds-4",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-chuui",
    kana: "ちゅうい",
    romaji: "chuui",
    meaningCopyId: "anchor-chuui-meaning",
    firstTeachLessonId: "sounds-4",
    countable: true,
    category: "noun",
  },
  {
    id: "anchor-ryokou",
    kana: "りょこう",
    romaji: "ryokou",
    meaningCopyId: "anchor-ryokou-meaning",
    firstTeachLessonId: "sounds-4",
    countable: true,
    category: "noun",
  },
]);

export const BASE_LEXEME_BY_ID: ReadonlyMap<string, BaseLexeme> =
  immutableReadonlyMap(BASE_LEXICON.map((lexeme) => [lexeme.id, lexeme]));

export interface BaseLexemeRecurrencePlan {
  readonly lexemeId: string;
  readonly plannedLessonIds: readonly string[];
}

function recurrence(
  lexemeIds: readonly string[],
  plannedLessonIds: readonly string[],
): readonly BaseLexemeRecurrencePlan[] {
  return lexemeIds.map((lexemeId) => ({ lexemeId, plannedLessonIds }));
}

export const BASE_TASK11_LEXEME_RECURRENCE_PLANS: readonly BaseLexemeRecurrencePlan[] =
  deepFreeze([
    ...recurrence(
      ["verb-kaku", "verb-yomu", "verb-nomu", "verb-kau"],
      ["argument-particles-1", "time-movement-3"],
    ),
    ...recurrence(
      ["verb-hataraku", "verb-asobu"],
      ["argument-particles-3", "time-movement-1"],
    ),
    ...recurrence(["verb-oyogu"], ["requests-connection-1"]),
    ...recurrence(["verb-taberu", "verb-miru"], ["argument-particles-1"]),
    ...recurrence(["verb-kaeru", "verb-kuru"], ["argument-particles-2"]),
    ...recurrence(["verb-suru"], ["time-movement-4"]),
    ...recurrence(["verb-benkyou-suru"], ["argument-particles-3"]),
    ...recurrence(
      ["verb-denwa-suru", "verb-sanpo-suru", "verb-matsu"],
      ["requests-connection-1"],
    ),
    ...recurrence(
      ["verb-yasumu", "verb-okiru", "verb-neru", "verb-aruku"],
      ["time-movement-1", "time-movement-2"],
    ),
    ...recurrence(
      ["verb-kiku", "verb-tsukuru", "verb-au", "verb-utau", "verb-hanasu"],
      ["time-movement-4", "requests-connection-2"],
    ),
    ...recurrence(["verb-iku"], ["argument-particles-2"]),
    ...recurrence(
      ["noun-gohan", "noun-mizu", "noun-kudamono"],
      ["copula-adjectives-3"],
    ),
    ...recurrence(
      ["noun-tegami", "noun-zasshi"],
      ["requests-connection-2"],
    ),
    ...recurrence(
      ["noun-eki", "noun-daigaku", "noun-byouin", "noun-mise"],
      ["existence-location-4"],
    ),
    ...recurrence(
      ["noun-toshokan", "noun-kouen"],
      ["existence-location-4"],
    ),
    ...recurrence(
      ["noun-densha", "noun-jitensha", "noun-enpitsu"],
      ["requests-connection-2"],
    ),
    ...recurrence(
      ["noun-shokudou", "noun-jimusho"],
      ["existence-location-4"],
    ),
    ...recurrence(["noun-kasa", "noun-nikki"], ["requests-connection-2"]),
    ...recurrence(
      ["verb-hashiru", "verb-ryokou-suru", "verb-ryouri-suru", "verb-dekakeru"],
      ["requests-connection-1", "base-synthesis-3"],
    ),
    ...recurrence(
      [
        "noun-kyou",
        "noun-ashita",
        "noun-getsuyoubi",
        "noun-shichiji",
        "noun-kuji",
        "noun-goji",
      ],
      ["time-movement-3", "time-movement-4"],
    ),
    ...recurrence(
      ["noun-kinou", "noun-senshuu", "noun-konshuu", "noun-raishuu"],
      ["time-movement-4", "base-synthesis-3"],
    ),
    ...recurrence(
      ["noun-kaigi", "noun-shigoto", "noun-yotei"],
      ["base-synthesis-3"],
    ),
    ...recurrence(
      [
        "noun-hirugohan",
        "noun-ban",
        "noun-kesa",
        "noun-konban",
        "noun-nichiyoubi",
      ],
      ["requests-connection-3", "base-synthesis-3"],
    ),
  ]);

export const BASE_TASK11_LEXEME_RECURRENCE_BY_ID: ReadonlyMap<
  string,
  BaseLexemeRecurrencePlan
> = immutableReadonlyMap(
  BASE_TASK11_LEXEME_RECURRENCE_PLANS.map((plan) => [plan.lexemeId, plan]),
);

export function baseLexemeById(id: string): BaseLexeme | undefined {
  return BASE_LEXEME_BY_ID.get(id);
}
