import { deepFreeze } from "../../foundations/deepFreeze";
import type { BaseNavigationCopy } from "./en";

export const baseNavigationCopyIt: BaseNavigationCopy = deepFreeze({
  modules: {
    sounds: { title: "Suoni e scrittura" },
    "sentence-foundations": { title: "Fondamenti della frase" },
    "topic-questions": { title: "Temi e domande" },
    "polite-verbs": { title: "Azioni cortesi" },
    "argument-particles": { title: "Ruoli e particelle" },
    "time-movement": { title: "Tempo e movimento" },
    "copula-adjectives": { title: "Descrizione e collegamento" },
    "existence-location": { title: "Esistenza e posizione" },
    "requests-connection": { title: "Richieste e collegamento" },
    "base-synthesis": { title: "Sintesi delle basi" },
  },
  lessons: {
    "sounds-1": { title: "Ascoltare i suoni giapponesi" },
    "sounds-2": { title: "Leggere gli schemi in hiragana" },
    "sounds-3": { title: "Notare i cambiamenti di suono" },
    "sounds-4": { title: "Leggere il katakana nel contesto" },
    "sentence-foundations-1": { title: "Costruire una frase breve" },
    "sentence-foundations-2": { title: "Nominare persone e cose" },
    "sentence-foundations-3": { title: "Scegliere un riferimento naturale" },
    "sentence-foundations-4": { title: "Scambiare informazioni semplici" },
    "topic-questions-1": { title: "Impostare un tema" },
    "topic-questions-2": { title: "Dare una risposta mirata" },
    "topic-questions-3": { title: "Chiedere chi, cosa e dove" },
    "topic-questions-4": { title: "Indicare persone e cose" },
    "polite-verbs-1": { title: "Riconoscere parole d'azione" },
    "polite-verbs-2": { title: "Parlare di un oggetto" },
    "polite-verbs-3": { title: "Dire un'azione con cortesia" },
    "polite-verbs-4": { title: "Collocare un'azione" },
    "argument-particles-1": { title: "Segnalare la persona coinvolta" },
    "argument-particles-2": { title: "Segnalare un oggetto" },
    "argument-particles-3": { title: "Segnalare una destinazione" },
    "argument-particles-4": { title: "Collegare i ruoli della frase" },
    "time-movement-1": { title: "Collocare un evento nel tempo" },
    "time-movement-2": { title: "Parlare di una routine" },
    "time-movement-3": { title: "Parlare di prima e dopo" },
    "time-movement-4": { title: "Descrivere un piccolo percorso" },
    "copula-adjectives-1": { title: "Descrivere con una copula" },
    "copula-adjectives-2": { title: "Aggiungere una qualità semplice" },
    "copula-adjectives-3": { title: "Collegare due descrizioni" },
    "copula-adjectives-4": { title: "Confrontare dettagli familiari" },
    "existence-location-1": { title: "Dire che qualcosa è presente" },
    "existence-location-2": { title: "Collocare una persona o una cosa" },
    "existence-location-3": { title: "Chiedere cosa c'è intorno" },
    "existence-location-4": { title: "Descrivere un luogo familiare" },
    "requests-connection-1": { title: "Fare una richiesta semplice" },
    "requests-connection-2": { title: "Rispondere con disponibilità" },
    "requests-connection-3": { title: "Collegare due idee brevi" },
    "requests-connection-4": { title: "Gestire un piccolo scambio" },
    "base-synthesis-1": { title: "Presentarsi con chiarezza" },
    "base-synthesis-2": { title: "Fare e rispondere alle domande di base" },
    "base-synthesis-3": { title: "Gestire una situazione familiare" },
    "base-synthesis-4": { title: "Combinare gli schemi fondamentali" },
  },
  objectives: {
    "a1-can-do-sounds-descriptor":
      "So riconoscere e leggere gli schemi di suono e scrittura usati nel corso di base.",
    "a1-can-do-sentence-foundations-descriptor":
      "So costruire frasi brevi e cortesi per identificare persone e cose in uno scambio familiare.",
    "a1-can-do-topic-questions-descriptor":
      "So impostare un tema e fare o rispondere a domande semplici su persone e cose familiari.",
    "a1-can-do-polite-verbs-descriptor":
      "So usare una breve frase d'azione cortese per una persona, un oggetto o un luogo familiare.",
    "base-can-do-argument-particles-descriptor":
      "So usare marcatori di ruolo di base per rendere più chiaro un breve messaggio familiare.",
    "a1-can-do-time-movement-descriptor":
      "So collocare un'attività familiare nel tempo e descrivere un movimento o una routine semplice.",
    "base-can-do-copula-adjectives-descriptor":
      "So creare una breve descrizione collegando informazioni familiari su identità e qualità.",
    "base-can-do-existence-location-descriptor":
      "So dire che una persona o una cosa familiare è presente e indicarne una semplice posizione.",
    "base-can-do-requests-connection-descriptor":
      "So fare o rispondere a una richiesta pratica semplice e collegare brevi idee familiari.",
    "base-can-do-synthesis-descriptor":
      "So combinare gli schemi fondamentali in un breve scambio quotidiano guidato.",
  },
  outcomes: {
    "base-module-outcome-sounds":
      "Usa l'attenzione a suoni e scrittura per affrontare con cura parole giapponesi brevi.",
    "base-module-outcome-sentence-foundations":
      "Costruisci brevi frasi cortesi di identità su persone e cose familiari.",
    "base-module-outcome-topic-questions":
      "Guida un breve scambio con un tema e semplici parole interrogative.",
    "base-module-outcome-polite-verbs":
      "Descrivi azioni familiari in brevi frasi cortesi.",
    "base-module-outcome-argument-particles":
      "Rendi più chiari i ruoli familiari nella frase con marcatori di collegamento di base.",
    "base-module-outcome-time-movement":
      "Parla in modo semplice di tempo, routine e movimento.",
    "base-module-outcome-copula-adjectives":
      "Descrivi persone e cose familiari con brevi affermazioni collegate.",
    "base-module-outcome-existence-location":
      "Di' cosa è presente e dove si trova in un luogo familiare.",
    "base-module-outcome-requests-connection":
      "Partecipa a un piccolo scambio pratico con una richiesta e una risposta.",
    "base-module-outcome-base-synthesis":
      "Usa insieme i meccanismi fondamentali in uno scambio quotidiano guidato.",
  },
  content: {
    "base-audio-failed":
      "La registrazione canonica non è stata riprodotta. Kana, divisione in more e significato restano visibili.",
    "base-audio-unavailable":
      "La registrazione canonica non è disponibile. Non viene sostituita da una voce del browser.",
    "base-audio-retry": "Riprova la registrazione canonica",
    "base-sounds-feedback-accepted": "Il suono o la lettura corrisponde all'obiettivo.",
    "base-sounds-feedback-retry": "Confronta i kana visibili e la divisione in more, poi riprova.",
    "sounds-1-recap": "Hai distinto le cinque vocali, il gojuon di base e tutti i 46 hiragana moderni.",
    "sounds-1-phonetic-explanation": "La mora è un'unità ritmica. Parti dall'hiragana e qui conta ogni kana di base come una mora.",
    "sounds-1-contrast-map": "Confronta la qualità delle vocali, poi segui ogni riga gojuon non sonora.",
    "sounds-2-recap": "Hai confrontato grafie non sonore, con dakuten e con handakuten senza inventare una distinzione sonora universale per じ/ぢ o ず/づ.",
    "sounds-2-phonetic-explanation": "Il dakuten sonorizza una riga; l'handakuten segna la riga p. じ/ぢ e ず/づ restano distinzioni ortografiche importanti.",
    "sounds-2-contrast-map": "Confronta か/が, さ/ざ, た/だ e は/ば/ぱ, poi riconosci じ/ぢ e ず/づ.",
    "sounds-3-recap": "Hai contato vocali lunghe, piccolo っ e ん moraica come unità ritmiche.",
    "sounds-3-phonetic-explanation": "Il numero di caratteri kana non coincide sempre con le more: vocali lunghe, piccolo っ e ん portano ritmo.",
    "sounds-3-contrast-map": "Confronta vocali brevi/lunghe, consonanti semplici/geminate e forme con o senza ん moraica.",
    "sounds-4-recap": "Hai letto gli yoon comuni come una mora e usato un piccolo ponte pratico verso il katakana.",
    "sounds-4-phonetic-explanation": "Un kana grande più il piccolo ゃ, ゅ o ょ forma una sola mora yoon.",
    "sounds-4-contrast-map": "Confronta gli yoon comuni e riporta solo il gruppo limitato di katakana all'hiragana noto.",
    "snd1-discriminate-vowels-instruction": "Scegli la vocale anteriore che completa il contrasto mostrato con あ.",
    "snd1-segment-asa-instruction": "Dividi あさ nelle sue due more.",
    "snd1-recognize-gojuon-instruction": "Seleziona la riga hiragana che corrisponde ai suoni proposti.",
    "snd1-map-hiragana-row-instruction": "Associa i suoni in ordine alla riga hiragana corretta.",
    "snd1-match-ie-instruction": "Associa le more visibili alla parola-ancora いえ.",
    "snd1-assemble-umi-instruction": "Componi う・み nella parola-ancora.",
    "snd1-listen-u-instruction": "Ascolta e identifica う tra le cinque vocali.",
    "snd1-read-neko-instruction": "Leggi ad alta voce la parola-ancora ねこ.",
    "snd2-discriminate-kaga-instruction": "Scegli la compagna sonora della か non sonora.",
    "snd2-segment-kagi-instruction": "Dividi la parola-ancora かぎ in more.",
    "snd2-recognize-jidi-instruction": "Scegli la sequenza che conserva tutte e quattro le grafie じ, ぢ, ず e づ.",
    "snd2-map-dakuten-instruction": "Associa i kana senza segno alle forme con dakuten o handakuten.",
    "snd2-match-kaze-instruction": "Associa le more visibili alla parola-ancora かぜ.",
    "snd2-assemble-denwa-instruction": "Componi で・ん・わ mantenendo ん come una mora.",
    "snd2-listen-kaga-instruction": "Ascolta e identifica la が sonora invece della か non sonora.",
    "snd2-read-panpu-instruction": "Leggi ad alta voce ぱ e ぷ con handakuten.",
    "snd3-discriminate-obasan-instruction": "Scegli la compagna con vocale lunga di おばさん.",
    "snd3-segment-gakkou-instruction": "Dividi がっこう contando il piccolo っ e la う della vocale lunga.",
    "snd3-recognize-small-tsu-instruction": "Riconosci la parola che contiene il piccolo っ.",
    "snd3-map-moraic-n-instruction": "Associa la ん moraica finale al proprio spazio ritmico.",
    "snd3-match-hon-instruction": "Associa ほ・ん alla parola-ancora ほん.",
    "snd3-assemble-kippu-instruction": "Componi き・っ・ぷ con tre unità ritmiche.",
    "snd3-listen-kan-instruction": "Ascolta e identifica かん invece di か.",
    "snd3-read-obaasan-instruction": "Leggi おばあさん conservando tutte e cinque le more.",
    "snd4-discriminate-yoon-instruction": "Scegli lo yoon di una mora formato correttamente con inizio sh.",
    "snd4-segment-ryokou-instruction": "Dividi りょこう contando りょ come una mora.",
    "snd4-recognize-small-yoon-instruction": "Riconosci i piccoli ゃ, ゅ e ょ negli yoon comuni.",
    "snd4-map-katakana-instruction": "Associa gli esempi limitati ア, カ e コ all'hiragana.",
    "snd4-match-shashin-instruction": "Associa le more visibili しゃ・し・ん alla parola-ancora しゃしん.",
    "snd4-assemble-kyaku-instruction": "Componi きゃ・く mantenendo きゃ come una mora.",
    "snd4-listen-nyuryo-instruction": "Ascolta e distingui にゅ da りょ.",
    "snd4-read-chuui-instruction": "Leggi ちゅうい contando ちゅ come una mora e う come un'altra.",
    "anchor-asa-meaning": "mattina",
    "anchor-ie-meaning": "casa",
    "anchor-umi-meaning": "mare",
    "anchor-neko-meaning": "gatto",
    "anchor-kagi-meaning": "chiave",
    "anchor-kaze-meaning": "vento",
    "anchor-denwa-meaning": "telefono",
    "anchor-pan-meaning": "pane",
    "anchor-obaasan-meaning": "nonna",
    "anchor-gakkou-meaning": "scuola",
    "anchor-hon-meaning": "libro",
    "anchor-kippu-meaning": "biglietto",
    "anchor-kyaku-meaning": "ospite; cliente",
    "anchor-shashin-meaning": "fotografia",
    "anchor-chuui-meaning": "attenzione; cautela",
    "anchor-ryokou-meaning": "viaggio",
  },
});
