import { curriculumExamples } from "../examples";

/**
 * English curriculum copy (design spec §9.1, §17.1). This catalog owns only
 * learner-facing prose: module titles/outcomes, lesson instructions, and
 * natural intent translations of the shared Japanese examples. It never stores
 * Japanese source text — that lives once in the example catalog — and its key
 * set is identical to the Italian catalog so a missing string is a validation
 * failure, never a silent fallback.
 *
 * Persona facts stay coherent with the shared catalog: Yuki is the student who
 * introduces herself, Ken an office worker, and Mina a teacher.
 */

interface LessonCopy {
  readonly title: string;
  readonly objective: string;
  readonly rule: string;
  readonly comparison: string;
  readonly guided: string;
  readonly spoken: string;
  readonly recap: string;
}

const LESSON_FIELDS: readonly (keyof LessonCopy)[] = [
  "title",
  "objective",
  "rule",
  "comparison",
  "guided",
  "spoken",
  "recap",
];

const modules: Record<string, { title: string; outcome: string }> = {
  sounds: {
    title: "Sounds, hiragana, and the katakana bridge",
    outcome:
      "Read and reproduce the course's essential hiragana and recognise assisted katakana loanwords.",
  },
  introductions: {
    title: "Introducing oneself",
    outcome:
      "Give your name, origin, languages, occupation, and age, and follow the same introduction from others.",
  },
  "essential-questions": {
    title: "Essential questions",
    outcome:
      "Ask and answer who, what, where, when, which, how, and how much, plus simple yes/no questions.",
  },
  actions: {
    title: "Actions and objects",
    outcome:
      "Build polite action sentences with objects and familiar companions.",
  },
  routines: {
    title: "Routines, clock time, and frequency",
    outcome:
      "Describe a day with clock time, days of the week, frequency, and recurring actions.",
  },
  "past-negative": {
    title: "Past and negative",
    outcome:
      "Move familiar sentences across non-past/past and affirmative/negative.",
  },
  places: {
    title: "Places, movement, and transport",
    outcome:
      "Move to and from places, act in them, board and get off transport, and ask the way.",
  },
  people: {
    title: "People, family, and relationships",
    outcome:
      "Identify people, describe basic relationships, and arrange simple shared plans.",
  },
  descriptions: {
    title: "Descriptions, preferences, and weather",
    outcome:
      "Describe familiar things and conditions and say what you like, dislike, and prefer.",
  },
  shopping: {
    title: "Shopping, quantities, and requests",
    outcome:
      "Ask prices, choose quantities, compare simple options, and make polite requests.",
  },
  "existence-needs": {
    title: "Existence, position, and needs",
    outcome:
      "Locate people and things, describe position, and state what you need.",
  },
  capstones: {
    title: "Practical synthesis",
    outcome:
      "Recombine everything in three bounded capstones: a self-introduction, an everyday outing, and a travel day.",
  },
};

const lessons: Record<string, LessonCopy> = {
  "sounds-1": {
    title: "Greetings through the day",
    objective: "Greet people correctly at any time of day.",
    rule: "Japanese greetings change with the time of day.",
    comparison: "‘Good morning’ gives way to ‘good evening’ as the day moves on.",
    guided: "Read each greeting aloud and match it to its time.",
    spoken: "Say the midday greeting clearly.",
    recap: "You can now greet people from morning to night.",
  },
  "sounds-2": {
    title: "Courtesy words",
    objective: "Thank, apologise, and answer yes or no.",
    rule: "A few set words carry most everyday courtesy.",
    comparison: "‘Thank you’ and ‘excuse me’ open very different exchanges.",
    guided: "Pair each courtesy word with a situation.",
    spoken: "Say ‘yes’ clearly and politely.",
    recap: "You can thank, apologise, and confirm.",
  },
  "sounds-3": {
    title: "Meeting people",
    objective: "Open a first meeting politely.",
    rule: "Two set phrases frame every first meeting.",
    comparison: "‘Nice to meet you’ opens; ‘I look forward to it’ closes.",
    guided: "Build the full opening from its two phrases.",
    spoken: "Say the full first-meeting greeting.",
    recap: "You can open a first meeting.",
  },
  "sounds-4": {
    title: "Katakana bridge: everyday loanwords",
    objective: "Read common katakana food and home words with reading help.",
    rule: "Loanwords use katakana; the hiragana reading helps you at first.",
    comparison: "‘Coffee’ and ‘juice’ share the same katakana rhythm.",
    guided: "Read each loanword using its hiragana aid.",
    spoken: "Say ‘milk’ from its katakana.",
    recap: "You can read five everyday katakana words.",
  },
  "sounds-5": {
    title: "Katakana bridge: places and transport",
    objective: "Read katakana transport and place words.",
    rule: "Katakana also spells transport and places you will meet often.",
    comparison: "‘Radio’ and ‘camera’ both show a katakana long vowel.",
    guided: "Read each katakana word with its reading.",
    spoken: "Say ‘bus’ from its katakana.",
    recap: "You can read five more katakana words.",
  },
  "introductions-1": {
    title: "I am…",
    objective: "State who you are with the topic and the copula.",
    rule: "Mark the topic with wa and close the sentence with desu.",
    comparison: "Only the topic changes from ‘I’ to ‘you’.",
    guided: "Build ‘My name is Yuki.’",
    spoken: "Introduce yourself as a student.",
    recap: "You can say who someone is.",
  },
  "introductions-2": {
    title: "Where I'm from and what I do",
    objective: "Give origin, occupation, and age, and drop a known topic.",
    rule: "Once the topic is known you may omit it; ni marks where you live.",
    comparison: "The origin switches from Italy to America.",
    guided: "Build ‘I live in Italy.’",
    spoken: "Say where you live.",
    recap: "You can state origin, job, and age.",
  },
  "introductions-3": {
    title: "What I study and understand",
    objective: "Say what you study, do, and understand using o.",
    rule: "Mark the object of an action with o.",
    comparison: "The studied language switches from Japanese to English.",
    guided: "Build ‘I study Japanese.’",
    spoken: "Say what you study.",
    recap: "You can talk about study and work.",
  },
  "essential-questions-1": {
    title: "This, that, and yes/no",
    objective: "Point things out and ask yes/no questions.",
    rule: "kore/sore/are point things out; ka turns a statement into a question.",
    comparison: "Adding ka turns ‘This is coffee’ into a question.",
    guided: "Turn ‘This is coffee.’ into a question.",
    spoken: "Ask whether that camera is Japanese.",
    recap: "You can point things out and ask yes/no.",
  },
  "essential-questions-2": {
    title: "Who, what, and where",
    objective: "Ask who, what, and where.",
    rule: "A question word replaces the unknown part of a sentence.",
    comparison: "‘Where is the restaurant?’ is answered by ‘here’.",
    guided: "Ask where someone goes.",
    spoken: "Ask where the restaurant is.",
    recap: "You can ask who, what, and where.",
  },
  "essential-questions-3": {
    title: "When, why, and how much",
    objective: "Ask when, why, how much, and how many.",
    rule: "More question words cover time, reason, and quantity.",
    comparison: "‘When do you come?’ becomes ‘why do you come?’.",
    guided: "Ask the price of a coffee.",
    spoken: "Ask how much the coffee is.",
    recap: "You can ask about time, reason, and price.",
  },
  "actions-1": {
    title: "Eating and drinking",
    objective: "Say what you eat and drink, and where.",
    rule: "de marks where an action happens.",
    comparison: "Adding a place puts the meal ‘at the restaurant’.",
    guided: "Build ‘I drink water.’",
    spoken: "Say that you drink water.",
    recap: "You can talk about eating and drinking.",
  },
  "actions-2": {
    title: "Reading, watching, and with whom",
    objective: "Say what you read and watch, and with whom.",
    rule: "to marks the person you do something with.",
    comparison: "The action moves from reading alone to watching with a friend.",
    guided: "Build ‘I write a letter with a friend.’",
    spoken: "Say you watch a movie with a friend.",
    recap: "You can act together with someone.",
  },
  "actions-3": {
    title: "Buying, using, and taking",
    objective: "Say what you buy, use, and take.",
    rule: "The same o pattern covers many everyday actions.",
    comparison: "Buying a bag becomes using a pen.",
    guided: "Build ‘I take a photo.’",
    spoken: "Say that you take a photo.",
    recap: "You can buy, use, and take things.",
  },
  "routines-1": {
    title: "Waking and sleeping",
    objective: "Say when you wake and sleep.",
    rule: "ni marks a clock time.",
    comparison: "Waking in the morning contrasts with sleeping at night.",
    guided: "Build ‘I eat breakfast in the morning.’",
    spoken: "Say when you wake up.",
    recap: "You can place actions on the clock.",
  },
  "routines-2": {
    title: "How often",
    objective: "Say how often you do things.",
    rule: "A frequency word sits before the verb.",
    comparison: "‘Every day’ becomes ‘sometimes’.",
    guided: "Build ‘I always watch a movie on the weekend.’",
    spoken: "Say what you often do.",
    recap: "You can describe frequency.",
  },
  "routines-3": {
    title: "A day in order",
    objective: "Sequence a day with days and times.",
    rule: "Days and times combine to sketch a routine.",
    comparison: "Morning music contrasts with an evening phone call.",
    guided: "Build ‘I study Japanese on Monday.’",
    spoken: "Say what you do on Monday.",
    recap: "You can describe a whole day.",
  },
  "past-negative-1": {
    title: "Yesterday",
    objective: "Put familiar actions into the past.",
    rule: "masu becomes mashita for a past action.",
    comparison: "‘I watch’ today becomes ‘I watched’ yesterday.",
    guided: "Build ‘Last week I did a test.’",
    spoken: "Say what you did yesterday.",
    recap: "You can talk about the past.",
  },
  "past-negative-2": {
    title: "Not today",
    objective: "Say what you don't or won't do.",
    rule: "masu becomes masen for the negative.",
    comparison: "‘I do homework’ becomes ‘I don't do homework’.",
    guided: "Build ‘Tonight I won't go to the meeting.’",
    spoken: "Say what you won't do today.",
    recap: "You can decline and negate.",
  },
  "past-negative-3": {
    title: "It didn't happen",
    objective: "Say what didn't happen in the past.",
    rule: "masen-deshita is the past negative.",
    comparison: "‘I met a friend’ becomes ‘I didn't meet a friend’.",
    guided: "Build ‘On my birthday I asked the way.’",
    spoken: "Say what you didn't do last month.",
    recap: "You can handle all four tense–polarity forms.",
  },
  "places-1": {
    title: "Coming and going",
    objective: "Say where you go, walk, and return.",
    rule: "e marks the direction you head.",
    comparison: "Returning home contrasts with walking to the station.",
    guided: "Build ‘I go to the town park.’",
    spoken: "Say you go to the park.",
    recap: "You can move toward places.",
  },
  "places-2": {
    title: "In and out, and from where",
    objective: "Enter and leave places and say where from.",
    rule: "kara marks where movement starts.",
    comparison: "Entering the shop contrasts with leaving it.",
    guided: "Build ‘I go to the bank and the post office.’",
    spoken: "Say you enter the shop.",
    recap: "You can enter, leave, and start from a place.",
  },
  "places-3": {
    title: "Getting around",
    objective: "Board and get off transport.",
    rule: "ni marks the transport you board.",
    comparison: "Boarding the train contrasts with getting off it.",
    guided: "Build ‘I take a taxi to the airport.’",
    spoken: "Say you board the train.",
    recap: "You can use transport.",
  },
  "places-4": {
    title: "Carrying and asking the way",
    objective: "Carry things and ask the way.",
    rule: "Familiar patterns combine to ask for directions.",
    comparison: "Carrying a bag contrasts with asking the way.",
    guided: "Ask where the station is.",
    spoken: "Ask where the station is.",
    recap: "You can ask and answer route questions.",
  },
  "people-1": {
    title: "My family",
    objective: "Name family members and teach someone.",
    rule: "ni marks the person who receives an action.",
    comparison: "‘This is my family’ narrows to ‘this is my father’.",
    guided: "Build ‘I teach Japanese to a friend.’",
    spoken: "Say you teach a friend.",
    recap: "You can name family and address people.",
  },
  "people-2": {
    title: "Giving and receiving",
    objective: "Say who you give to and receive from.",
    rule: "ageru gives, morau receives, and ni marks the partner.",
    comparison: "Giving a letter contrasts with receiving one.",
    guided: "Build ‘I read a book to my son and daughter.’",
    spoken: "Say you give a letter to a friend.",
    recap: "You can give and receive.",
  },
  "people-3": {
    title: "Let's make plans",
    objective: "Suggest and offer shared actions.",
    rule: "mashou suggests; mashou-ka offers.",
    comparison: "‘Let's go’ becomes ‘shall I carry it?’.",
    guided: "Build ‘Let's eat in the park.’",
    spoken: "Suggest eating together.",
    recap: "You can arrange simple plans.",
  },
  "descriptions-1": {
    title: "Big and small",
    objective: "Describe things with i- and na-adjectives.",
    rule: "i-adjectives and na-adjectives describe nouns.",
    comparison: "A big house becomes a small house.",
    guided: "Build ‘I sit in a pretty room.’",
    spoken: "Describe a small house.",
    recap: "You can describe things.",
  },
  "descriptions-2": {
    title: "Likes and dislikes",
    objective: "Say what you like, dislike, and are good at.",
    rule: "ga marks what you like or are good at.",
    comparison: "Liking Japanese contrasts with disliking movies.",
    guided: "Build ‘I like music; I'm good at Japanese.’",
    spoken: "Say what you like.",
    recap: "You can express preferences.",
  },
  "descriptions-3": {
    title: "Comparing, and yesterday's weather",
    objective: "Compare options and describe past states.",
    rule: "yori compares; an i-adjective takes katta in the past.",
    comparison:
      "Only the adjective changes: the bus goes from cheaper to more expensive than the train.",
    guided: "Build ‘I learn Japanese.’",
    spoken: "Say that you learn Japanese.",
    recap: "You can compare and describe the past.",
  },
  "shopping-1": {
    title: "How many",
    objective: "Count and choose quantities.",
    rule: "A counter follows the noun to give an amount.",
    comparison: "One apple becomes three apples.",
    guided: "Ask how much a shirt is.",
    spoken: "Say you buy three apples.",
    recap: "You can choose quantities.",
  },
  "shopping-2": {
    title: "Please, and I'd like",
    objective: "Make polite requests and say what you want.",
    rule: "kudasai requests; tai says what you want.",
    comparison: "‘Water, please’ becomes ‘I want to drink coffee’.",
    guided: "Build ‘I want to buy fruit.’",
    spoken: "Ask for water politely.",
    recap: "You can request and state wants.",
  },
  "shopping-3": {
    title: "Borrow, open, close",
    objective: "Borrow, open, and close things.",
    rule: "Everyday transactions reuse the o pattern.",
    comparison: "Only the verb changes: opening the shop becomes closing it.",
    guided: "Build ‘I borrow a book from a friend.’",
    spoken: "Say you borrow a book.",
    recap: "You can handle small transactions.",
  },
  "existence-needs-1": {
    title: "What's where",
    objective: "Say where inanimate things are.",
    rule: "arimasu states a thing exists; position words say where.",
    comparison: "A book on the desk moves to a bag under it.",
    guided: "Build ‘There are keys and glasses beside the chair.’",
    spoken: "Say there is a book on the desk.",
    recap: "You can locate things.",
  },
  "existence-needs-2": {
    title: "Who's where",
    objective: "Say where people are.",
    rule: "imasu states that a person or animal exists.",
    comparison: "A person inside contrasts with a child in front.",
    guided: "Build ‘My family is in the next room.’",
    spoken: "Say a person is in the room.",
    recap: "You can locate people.",
  },
  "existence-needs-3": {
    title: "What I need",
    objective: "State immediate needs.",
    rule: "iru states a need; hoshii says you want a thing.",
    comparison: "Needing medicine contrasts with wanting water.",
    guided: "Build ‘I need a ticket and a passport.’",
    spoken: "Say you need medicine.",
    recap: "You can state needs.",
  },
  "capstones-orientation": {
    title: "Before the capstones",
    objective: "Review every gear before the three capstones.",
    rule: "The capstones only recombine what you already know.",
    comparison: "A statement becomes a question with ka.",
    guided: "Build ‘I study Japanese every day.’",
    spoken: "Introduce yourself in one line.",
    recap: "You are ready for the capstones.",
  },
  "capstones-self-introduction": {
    title: "Capstone: self-introduction",
    objective: "Introduce yourself and ask reciprocal questions.",
    rule: "Combine identity, study, and questions in one exchange.",
    comparison: "A plain introduction gains an origin and a question.",
    guided: "Build ‘I work; do you understand English?’",
    spoken: "Give your full self-introduction.",
    recap: "You completed the self-introduction capstone.",
  },
  "capstones-everyday-outing": {
    title: "Capstone: an everyday outing",
    objective: "Coordinate time, people, and shopping on an outing.",
    rule: "Chain transport, meeting, and buying into one outing.",
    comparison: "Taking the bus leads into eating with a friend.",
    guided: "Build ‘I buy fruit at the convenience store and go home.’",
    spoken: "Describe your outing.",
    recap: "You completed the everyday-outing capstone.",
  },
  "capstones-travel-day": {
    title: "Capstone: a travel day",
    objective: "Move, use transport, and solve a travel need.",
    rule: "Combine movement, needs, and requests across a journey.",
    comparison: "Boarding the train leads into needing a map.",
    guided: "Build ‘I use my passport at the hotel and open the door.’",
    spoken: "Describe your travel day.",
    recap: "You completed the travel-day capstone.",
  },
};

const exampleTranslations: Record<string, string> = {
  "sounds-1-base": "Good morning.",
  "sounds-1-changed": "Good evening.",
  "sounds-1-say": "Hello.",
  "sounds-1-r1": "Goodbye.",
  "sounds-2-base": "Thank you.",
  "sounds-2-changed": "Excuse me.",
  "sounds-2-say": "Yes.",
  "sounds-2-r1": "No.",
  "sounds-3-base": "Nice to meet you.",
  "sounds-3-changed": "I look forward to it.",
  "sounds-3-say": "Nice to meet you; I look forward to it.",
  "sounds-4-base": "coffee",
  "sounds-4-changed": "juice",
  "sounds-4-say": "milk",
  "sounds-4-r1": "bread",
  "sounds-4-r2": "television",
  "sounds-5-base": "radio",
  "sounds-5-changed": "camera",
  "sounds-5-say": "bus",
  "sounds-5-r1": "taxi",
  "sounds-5-r2": "restaurant",
  "introductions-1-base": "I am a student.",
  "introductions-1-changed": "You are a student.",
  "introductions-1-say": "My name is Yuki.",
  "introductions-1-r1": "My hometown is Japan.",
  "introductions-1-r2": "Mina is a Japanese teacher.",
  "introductions-2-base": "My hometown is Italy.",
  "introductions-2-changed": "My hometown is America.",
  "introductions-2-say": "I live in Italy.",
  "introductions-2-r1": "I am a doctor.",
  "introductions-2-r2": "Ken is an office worker.",
  "introductions-2-r3": "My age is twenty-five.",
  "introductions-2-r4": "My country is Japan.",
  "introductions-3-base": "I study Japanese.",
  "introductions-3-changed": "I study English.",
  "introductions-3-say": "I do my company job.",
  "introductions-3-r1": "I understand Japanese.",
  "introductions-3-r2": "I study my friend's language.",
  "introductions-3-r3": "I know the phone number.",
  "essential-questions-1-base": "This is coffee.",
  "essential-questions-1-changed": "Is this coffee?",
  "essential-questions-1-say": "Is that camera Japanese?",
  "essential-questions-1-r1": "Which one is my camera?",
  "essential-questions-1-r2": "that, that over there, and that radio",
  "essential-questions-2-base": "Where is the restaurant?",
  "essential-questions-2-changed": "The restaurant is here.",
  "essential-questions-2-say": "Where do you go?",
  "essential-questions-2-r1": "There is a restaurant.",
  "essential-questions-2-r2": "I go over there.",
  "essential-questions-2-r3": "What is that? Whose is it?",
  "essential-questions-3-base": "When do you come?",
  "essential-questions-3-changed": "Why do you come?",
  "essential-questions-3-say": "How much is this coffee?",
  "essential-questions-3-r1": "How many coffees?",
  "essential-questions-3-r2": "How is Japanese?",
  "actions-1-base": "I eat a meal.",
  "actions-1-changed": "I eat a meal at the restaurant.",
  "actions-1-say": "I drink water.",
  "actions-1-r1": "I drink tea at the restaurant.",
  "actions-2-base": "I read a book.",
  "actions-2-changed": "I watch a movie with a friend.",
  "actions-2-say": "I write a letter with a friend.",
  "actions-2-r1": "I read the newspaper.",
  "actions-2-r2": "I read my friend's letter.",
  "actions-3-base": "I buy a bag.",
  "actions-3-changed": "I use a pen.",
  "actions-3-say": "I take a photo.",
  "actions-3-r1": "I buy a notebook and a pencil.",
  "actions-3-r2": "I write an email.",
  "actions-3-r3": "I buy food and drinks.",
  "actions-3-r4": "I use this thing.",
  "routines-1-base": "I wake up at seven in the morning.",
  "routines-1-changed": "I go to sleep at eleven at night.",
  "routines-1-say": "I eat breakfast in the morning.",
  "routines-1-r1": "I drink tea at midday.",
  "routines-2-base": "I work every day.",
  "routines-2-changed": "I sometimes speak Japanese.",
  "routines-2-say": "I always watch a movie on the weekend.",
  "routines-2-r1": "I often read books.",
  "routines-3-base": "I listen to music in the morning.",
  "routines-3-changed": "I make a phone call at night.",
  "routines-3-say": "I study Japanese on Monday.",
  "routines-3-r1": "I talk with a friend on Sunday.",
  "routines-3-r2": "nine a.m. and half past three p.m.",
  "routines-3-r3": "I study Japanese for one hour.",
  "routines-3-r4": "I look at the clock.",
  "routines-3-r5": "I wake up at six oh five a.m.",
  "past-negative-1-base": "Yesterday I watched a movie with a friend.",
  "past-negative-1-changed": "Today I watch a movie with a friend.",
  "past-negative-1-say": "Last week I did a test.",
  "past-negative-1-r1": "This morning I read the newspaper.",
  "past-negative-1-r2": "Last year I studied Japanese.",
  "past-negative-2-base": "Today I do my homework.",
  "past-negative-2-changed": "Today I don't do my homework.",
  "past-negative-2-say": "Tonight I won't go to the meeting.",
  "past-negative-2-r1": "Next week I will wait for a friend.",
  "past-negative-3-base": "Last month I met a friend.",
  "past-negative-3-changed": "Last month I didn't meet a friend.",
  "past-negative-3-say": "On my birthday I asked the way.",
  "past-negative-3-r1":
    "This week and this month are days off; next month I go to Japan; this year I meet a friend.",
  "past-negative-3-r2": "Next year on a day off I will meet a friend.",
  "places-1-base": "I return home.",
  "places-1-changed": "I walk to the station.",
  "places-1-say": "I go to the town park.",
  "places-1-r1": "I return home from school.",
  "places-2-base": "I enter the shop.",
  "places-2-changed": "I leave the shop.",
  "places-2-say": "I go to the bank and the post office.",
  "places-2-r1": "I walk from the hospital.",
  "places-2-r2": "I read a book at the library.",
  "places-3-base": "I board the train at the station.",
  "places-3-changed": "I get off the train at the station.",
  "places-3-say": "I take a taxi to the airport.",
  "places-3-r1": "I go by subway and bus.",
  "places-3-r2": "car, bicycle, and airplane",
  "places-4-base": "I carry a bag.",
  "places-4-changed": "I ask for directions at the station.",
  "places-4-say": "Where is the station?",
  "places-4-r1": "I use the computer in the room.",
  "people-1-base": "This is my family.",
  "people-1-changed": "This person is my father.",
  "people-1-say": "I teach Japanese to a friend.",
  "people-1-r1": "My mother, older sister, and younger sister are family.",
  "people-1-r2": "My older and younger brothers are students.",
  "people-1-r3": "My parents walk in the park.",
  "people-2-base": "I give a letter to a friend.",
  "people-2-changed": "I receive a letter from my father.",
  "people-2-say": "I read a book to my son and daughter.",
  "people-2-r1": "This is my grandfather and grandmother.",
  "people-2-r2": "The husband and wife watch a movie.",
  "people-2-r3": "I teach Japanese to the children.",
  "people-3-base": "Let's go to the park with a friend.",
  "people-3-changed": "Shall I carry your bag?",
  "people-3-say": "Let's eat in the park.",
  "people-3-r1": "He and she are friends.",
  "people-3-r2": "The man and the woman are teachers.",
  "people-3-r3": "I wait for the boy and the girl.",
  "descriptions-1-base": "It's a big house.",
  "descriptions-1-changed": "It's a small house.",
  "descriptions-1-say": "I sit in a pretty room.",
  "descriptions-1-r1": "a new car and an old bicycle",
  "descriptions-1-r2": "This book is interesting.",
  "descriptions-1-r3": "Difficult work is fun.",
  "descriptions-2-base": "I like Japanese.",
  "descriptions-2-changed": "I dislike movies.",
  "descriptions-2-say": "I like music; I'm good at Japanese.",
  "descriptions-2-r1": "This food is delicious.",
  "descriptions-2-r2": "Today's weather is good.",
  "descriptions-3-base": "The bus is cheaper than the train.",
  "descriptions-3-changed": "The bus is more expensive than the train.",
  "descriptions-3-say": "I learn Japanese.",
  "descriptions-3-r1": "The weather is hot; rain and clouds.",
  "descriptions-3-r2": "I stand in front of the teacher.",
  "descriptions-3-r3": "The easy job was fun.",
  "descriptions-3-r7": "Yesterday was cold.",
  "shopping-1-base": "I buy one apple.",
  "shopping-1-changed": "I buy three apples.",
  "shopping-1-say": "How much is this shirt?",
  "shopping-1-r1": "I buy two eggs and a little meat.",
  "shopping-1-r2": "I buy all the vegetables and fish.",
  "shopping-2-base": "Water, please.",
  "shopping-2-changed": "I want to drink coffee.",
  "shopping-2-say": "I want to buy fruit.",
  "shopping-2-r1": "Half a tea, please.",
  "shopping-2-r2": "I buy a lot of fruit at the supermarket.",
  "shopping-3-base": "I open the shop.",
  "shopping-3-changed": "I close the shop.",
  "shopping-3-say": "I borrow a book from a friend.",
  "shopping-3-r1": "I used all the money in my wallet.",
  "shopping-3-r2": "The price of the clothes is high.",
  "shopping-3-r3": "I ask for three hats and the size.",
  "shopping-3-r4": "one thousand yen and one hundred yen",
  "existence-needs-1-base": "There is a book on the desk.",
  "existence-needs-1-changed": "There is a bag under the desk.",
  "existence-needs-1-say": "There are keys and glasses beside the chair.",
  "existence-needs-1-r1": "There are glasses on the chair.",
  "existence-needs-1-r2": "There is a car outside.",
  "existence-needs-2-base": "There is a person in the room.",
  "existence-needs-2-changed": "There is a child in front of the house.",
  "existence-needs-2-say": "My family is in the next room.",
  "existence-needs-2-r1": "behind, right, left, and between",
  "existence-needs-2-r2": "A friend is near the station.",
  "existence-needs-3-base": "I need medicine.",
  "existence-needs-3-changed": "I want water.",
  "existence-needs-3-say": "I need a ticket and a passport.",
  "existence-needs-3-r1": "I need a map and an umbrella.",
  "existence-needs-3-r2": "There is a toilet in the hotel.",
  "capstones-orientation-base": "I am a Japanese student.",
  "capstones-orientation-changed": "Am I a Japanese student?",
  "capstones-orientation-say": "I study Japanese every day.",
  "capstones-self-introduction-base": "Nice to meet you, I'm Yuki.",
  "capstones-self-introduction-changed": "My hometown is Italy; I speak Japanese.",
  "capstones-self-introduction-say": "I work; do you understand English?",
  "capstones-self-introduction-r1": "I live in a house; my family is here.",
  "capstones-self-introduction-r2": "I meet a friend; I learn Japanese.",
  "capstones-self-introduction-r3":
    "I want to study Japanese; I don't speak English.",
  "capstones-everyday-outing-base": "I take the bus; I go to town.",
  "capstones-everyday-outing-changed": "I eat with a friend at the restaurant.",
  "capstones-everyday-outing-say":
    "I buy fruit at the convenience store; I return home.",
  "capstones-everyday-outing-r1": "I walk in the park; I take photos.",
  "capstones-everyday-outing-r2":
    "I wait for a friend at the station; let's watch a movie.",
  "capstones-everyday-outing-r3": "I listen to music; I call a friend.",
  "capstones-everyday-outing-r4":
    "The train is cheaper than the taxi; the movie was fun.",
  "capstones-everyday-outing-r5": "Shall I take a photo?",
  "capstones-travel-day-base":
    "I board the plane at the airport; I get off the train at the station.",
  "capstones-travel-day-changed": "I ask for directions; I need a map.",
  "capstones-travel-day-say":
    "I use my passport at the hotel; I open the door.",
  "capstones-travel-day-r1": "I borrow an umbrella; I carry a bag.",
  "capstones-travel-day-r2": "I enter the hotel; I close the window.",
  "capstones-travel-day-r3":
    "I return home; I write an email to a friend.",
  "capstones-travel-day-r4":
    "A ticket, please; I didn't understand the road.",
  "past-negative-1-r3": "This morning I woke up; I wrote a letter; I read the newspaper.",
  "past-negative-2-r2": "Tonight I won't work; I won't sleep.",
  "past-negative-3-r3": "I talked with a friend; I listened to music; I made a phone call.",
  "places-1-r2": "My friend lives in town; she speaks Japanese.",
  "places-4-r2": "I wait for a friend at the station; I take a photo.",
  "people-1-r4": "A friend comes to the house; I write a letter.",
  "people-1-r5": "My grandfather lives in Japan; he listens to music.",
  "people-2-r4": "I call a friend; I teach some words.",
  "people-2-r5": "I understand the child's words.",
  "people-3-r4": "I meet a friend in town; I carry a bag.",
  "descriptions-1-r4": "In the morning I wake up; every day I work; at night I sleep.",
  "descriptions-2-r3": "I give a book to a friend; I receive a book from my father.",
  "descriptions-3-r4": "I teach Japanese to the children; I take a photo.",
  "shopping-1-r3": "I enter the shop; I buy shoes; I leave the shop.",
  "shopping-2-r3": "I board the train at the station; I get off at the airport.",
  "shopping-2-r4": "At the shop I give money to a friend; I receive the change.",
  "shopping-3-r5": "I return home from the shop; I learn Japanese.",
  "shopping-3-r6": "I stand on the train; I sit on the chair.",
  "shopping-3-r7": "Every day I work at the shop; I borrow a book from a friend.",
  "shopping-3-r8": "I open the wallet; I close the wallet.",
  "existence-needs-1-r3": "I sit on the chair; I read a book.",
  "existence-needs-1-r4": "I get off the train at the station; I carry a bag.",
  "existence-needs-2-r3": "I stand in front of the door; I open the door.",
  "existence-needs-2-r4": "A friend comes to the station; I meet the friend.",
  "existence-needs-3-r3": "At the hotel I borrow an umbrella; I close the window.",
  "existence-needs-3-r4": "I enter the hotel; I leave the room.",
  "existence-needs-3-r5": "I give medicine to a friend; I receive a map from my father.",
  "existence-needs-3-r6": "I teach Japanese to the children; I learn Japanese.",
  "descriptions-3-r5": "At night I sleep at ten o'clock.",
  "people-3-r5": "I leave the shop; I carry a bag.",
  "existence-needs-2-r5": "My grandfather sits on the chair.",
  "existence-needs-3-r7": "I stand in front of the window.",
  "routines-3-r6": "Tomorrow I study Japanese.",
  "past-negative-3-r5": "I went to the birthday party.",
  "descriptions-2-r4": "Today I am busy.",
  "descriptions-3-r6": "This camera is expensive.",
};

function build(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [id, copy] of Object.entries(modules)) {
    out[`module.${id}.title`] = copy.title;
    out[`module.${id}.outcome`] = copy.outcome;
  }
  for (const [id, copy] of Object.entries(lessons)) {
    for (const field of LESSON_FIELDS) {
      out[`lesson.${id}.${field}`] = copy[field];
    }
  }
  for (const example of curriculumExamples) {
    out[`example.${example.id}.translation`] = exampleTranslations[example.id];
  }
  return out;
}

/** English learner-facing copy, keyed identically to the Italian catalog. */
export const en: Readonly<Record<string, string>> = Object.freeze(build());
