import { curriculumExamples } from "../examples";

/**
 * Italian curriculum copy (design spec §9.1, §17.1). Same key set as the
 * English catalog, translated for Italian learners. It owns only learner-facing
 * prose and never stores Japanese source text. Persona facts stay coherent with
 * the shared catalog: Yuki is the student who introduces herself, Ken an
 * office worker, and Mina a teacher.
 */

interface LessonCopy {
  readonly title: string;
  readonly objective: string;
  readonly rule: string;
  readonly comparison: string;
  readonly guided: string;
  readonly spoken: string;
  readonly recap: string;
}

const LESSON_FIELDS: readonly (keyof LessonCopy)[] = [
  "title",
  "objective",
  "rule",
  "comparison",
  "guided",
  "spoken",
  "recap",
];

const modules: Record<string, { title: string; outcome: string }> = {
  sounds: {
    title: "Suoni, hiragana e il ponte katakana",
    outcome:
      "Leggi e riproduci gli hiragana essenziali del corso e riconosci i prestiti in katakana con supporto alla lettura.",
  },
  introductions: {
    title: "Presentarsi",
    outcome:
      "Di' nome, provenienza, lingue, occupazione ed età, e comprendi la stessa presentazione dagli altri.",
  },
  "essential-questions": {
    title: "Domande essenziali",
    outcome:
      "Chiedi e rispondi a chi, cosa, dove, quando, quale, come e quanto, e semplici domande sì/no.",
  },
  actions: {
    title: "Azioni e oggetti",
    outcome:
      "Costruisci frasi d'azione cortesi con oggetti e compagni familiari.",
  },
  routines: {
    title: "Routine, orario e frequenza",
    outcome:
      "Descrivi una giornata con orario, giorni della settimana, frequenza e azioni ricorrenti.",
  },
  "past-negative": {
    title: "Passato e negativo",
    outcome:
      "Trasforma frasi familiari tra presente e passato e tra affermativo e negativo.",
  },
  places: {
    title: "Luoghi, movimento e trasporti",
    outcome:
      "Vai e torna dai luoghi, agisci lì, sali e scendi dai mezzi e chiedi la strada.",
  },
  people: {
    title: "Persone, famiglia e relazioni",
    outcome:
      "Identifica le persone, descrivi relazioni di base e organizza semplici piani condivisi.",
  },
  descriptions: {
    title: "Descrizioni, preferenze e meteo",
    outcome:
      "Descrivi cose e condizioni familiari e di' cosa ti piace, cosa non ti piace e cosa preferisci.",
  },
  shopping: {
    title: "Acquisti, quantità e richieste",
    outcome:
      "Chiedi i prezzi, scegli le quantità, confronta opzioni semplici e fai richieste cortesi.",
  },
  "existence-needs": {
    title: "Esistenza, posizione e bisogni",
    outcome:
      "Individua persone e cose, descrivi la posizione e di' ciò di cui hai bisogno.",
  },
  capstones: {
    title: "Sintesi pratica",
    outcome:
      "Ricombina tutto in tre prove finali circoscritte: una presentazione, un'uscita quotidiana e una giornata di viaggio.",
  },
};

const lessons: Record<string, LessonCopy> = {
  "sounds-1": {
    title: "Saluti nella giornata",
    objective: "Saluta correttamente a ogni ora del giorno.",
    rule: "I saluti giapponesi cambiano con l'ora del giorno.",
    comparison: "«Buongiorno» lascia il posto a «buonasera» col passare della giornata.",
    guided: "Leggi ogni saluto ad alta voce e abbinalo alla sua ora.",
    spoken: "Di' chiaramente il saluto di mezzogiorno.",
    recap: "Ora sai salutare dalla mattina alla sera.",
  },
  "sounds-2": {
    title: "Parole di cortesia",
    objective: "Ringrazia, scusati e rispondi sì o no.",
    rule: "Poche parole fisse coprono gran parte della cortesia quotidiana.",
    comparison: "«Grazie» e «scusa» aprono scambi molto diversi.",
    guided: "Abbina ogni parola di cortesia a una situazione.",
    spoken: "Di' «sì» in modo chiaro e cortese.",
    recap: "Sai ringraziare, scusarti e confermare.",
  },
  "sounds-3": {
    title: "Conoscere le persone",
    objective: "Apri un primo incontro con cortesia.",
    rule: "Due frasi fisse incorniciano ogni primo incontro.",
    comparison: "«Piacere» apre; «conto su di te» chiude.",
    guided: "Costruisci l'apertura completa dalle sue due frasi.",
    spoken: "Di' il saluto completo di un primo incontro.",
    recap: "Sai aprire un primo incontro.",
  },
  "sounds-4": {
    title: "Ponte katakana: prestiti di ogni giorno",
    objective: "Leggi comuni parole katakana di cibo e casa con l'aiuto alla lettura.",
    rule: "I prestiti usano il katakana; all'inizio la lettura in hiragana ti aiuta.",
    comparison: "«Caffè» e «succo» condividono lo stesso ritmo katakana.",
    guided: "Leggi ogni prestito usando il suo aiuto in hiragana.",
    spoken: "Di' «latte» dal suo katakana.",
    recap: "Sai leggere cinque parole katakana di ogni giorno.",
  },
  "sounds-5": {
    title: "Ponte katakana: luoghi e trasporti",
    objective: "Leggi parole katakana di trasporti e luoghi.",
    rule: "Il katakana scrive anche trasporti e luoghi che incontrerai spesso.",
    comparison: "«Radio» e «macchina fotografica» mostrano una vocale lunga in katakana.",
    guided: "Leggi ogni parola katakana con la sua lettura.",
    spoken: "Di' «autobus» dal suo katakana.",
    recap: "Sai leggere altre cinque parole katakana.",
  },
  "introductions-1": {
    title: "Io sono…",
    objective: "Di' chi sei con il tema e la copula.",
    rule: "Segna il tema con wa e chiudi la frase con desu.",
    comparison: "Cambia solo il tema, da «io» a «tu».",
    guided: "Costruisci «Mi chiamo Yuki».",
    spoken: "Presentati come studente.",
    recap: "Sai dire chi è qualcuno.",
  },
  "introductions-2": {
    title: "Da dove vengo e cosa faccio",
    objective: "Di' provenienza, occupazione ed età, e ometti un tema noto.",
    rule: "Quando il tema è noto puoi ometterlo; ni segna dove vivi.",
    comparison: "La provenienza passa dall'Italia all'America.",
    guided: "Costruisci «Vivo in Italia».",
    spoken: "Di' dove vivi.",
    recap: "Sai dire provenienza, lavoro ed età.",
  },
  "introductions-3": {
    title: "Cosa studio e capisco",
    objective: "Di' cosa studi, fai e capisci usando o.",
    rule: "Segna l'oggetto di un'azione con o.",
    comparison: "La lingua studiata passa dal giapponese all'inglese.",
    guided: "Costruisci «Studio giapponese».",
    spoken: "Di' cosa studi.",
    recap: "Sai parlare di studio e lavoro.",
  },
  "essential-questions-1": {
    title: "Questo, quello e sì/no",
    objective: "Indica le cose e fai domande sì/no.",
    rule: "kore/sore/are indicano; ka trasforma un'affermazione in domanda.",
    comparison: "Aggiungere ka trasforma «Questo è caffè» in una domanda.",
    guided: "Trasforma «Questo è caffè» in una domanda.",
    spoken: "Chiedi se quella macchina fotografica è giapponese.",
    recap: "Sai indicare le cose e fare domande sì/no.",
  },
  "essential-questions-2": {
    title: "Chi, cosa e dove",
    objective: "Chiedi chi, cosa e dove.",
    rule: "Una parola interrogativa sostituisce la parte sconosciuta della frase.",
    comparison: "«Dov'è il ristorante?» ha come risposta «qui».",
    guided: "Chiedi dove va qualcuno.",
    spoken: "Chiedi dov'è il ristorante.",
    recap: "Sai chiedere chi, cosa e dove.",
  },
  "essential-questions-3": {
    title: "Quando, perché e quanto",
    objective: "Chiedi quando, perché, quanto costa e quanti.",
    rule: "Altre parole interrogative coprono tempo, motivo e quantità.",
    comparison: "«Quando vieni?» diventa «perché vieni?».",
    guided: "Chiedi il prezzo di un caffè.",
    spoken: "Chiedi quanto costa il caffè.",
    recap: "Sai chiedere tempo, motivo e prezzo.",
  },
  "actions-1": {
    title: "Mangiare e bere",
    objective: "Di' cosa mangi e bevi, e dove.",
    rule: "de segna dove avviene un'azione.",
    comparison: "Aggiungere un luogo mette il pasto «al ristorante».",
    guided: "Costruisci «Bevo acqua».",
    spoken: "Di' che bevi acqua.",
    recap: "Sai parlare di mangiare e bere.",
  },
  "actions-2": {
    title: "Leggere, guardare e con chi",
    objective: "Di' cosa leggi e guardi, e con chi.",
    rule: "to segna la persona con cui fai qualcosa.",
    comparison: "L'azione passa dal leggere da solo al guardare con un amico.",
    guided: "Costruisci «Scrivo una lettera con un amico».",
    spoken: "Di' che guardi un film con un amico.",
    recap: "Sai agire insieme a qualcuno.",
  },
  "actions-3": {
    title: "Comprare, usare e prendere",
    objective: "Di' cosa compri, usi e prendi.",
    rule: "Lo stesso schema con o copre molte azioni quotidiane.",
    comparison: "Comprare una borsa diventa usare una penna.",
    guided: "Costruisci «Faccio una foto».",
    spoken: "Di' che fai una foto.",
    recap: "Sai comprare, usare e prendere cose.",
  },
  "routines-1": {
    title: "Svegliarsi e dormire",
    objective: "Di' quando ti svegli e dormi.",
    rule: "ni segna un orario.",
    comparison: "Svegliarsi al mattino contrasta col dormire di notte.",
    guided: "Costruisci «Faccio colazione al mattino».",
    spoken: "Di' quando ti svegli.",
    recap: "Sai collocare le azioni nell'orario.",
  },
  "routines-2": {
    title: "Con che frequenza",
    objective: "Di' con che frequenza fai le cose.",
    rule: "Un avverbio di frequenza sta prima del verbo.",
    comparison: "«Ogni giorno» diventa «a volte».",
    guided: "Costruisci «Guardo sempre un film nel fine settimana».",
    spoken: "Di' cosa fai spesso.",
    recap: "Sai descrivere la frequenza.",
  },
  "routines-3": {
    title: "Una giornata in ordine",
    objective: "Metti in sequenza una giornata con giorni e orari.",
    rule: "Giorni e orari si combinano per delineare una routine.",
    comparison: "La musica del mattino contrasta con una telefonata serale.",
    guided: "Costruisci «Studio giapponese il lunedì».",
    spoken: "Di' cosa fai il lunedì.",
    recap: "Sai descrivere un'intera giornata.",
  },
  "past-negative-1": {
    title: "Ieri",
    objective: "Metti al passato azioni familiari.",
    rule: "masu diventa mashita per un'azione passata.",
    comparison: "«Guardo» oggi diventa «ho guardato» ieri.",
    guided: "Costruisci «La settimana scorsa ho fatto un test».",
    spoken: "Di' cosa hai fatto ieri.",
    recap: "Sai parlare del passato.",
  },
  "past-negative-2": {
    title: "Oggi no",
    objective: "Di' cosa non fai o non farai.",
    rule: "masu diventa masen per il negativo.",
    comparison: "«Faccio i compiti» diventa «non faccio i compiti».",
    guided: "Costruisci «Stasera non vado alla riunione».",
    spoken: "Di' cosa non fai oggi.",
    recap: "Sai rifiutare e negare.",
  },
  "past-negative-3": {
    title: "Non è successo",
    objective: "Di' cosa non è successo nel passato.",
    rule: "masen-deshita è il passato negativo.",
    comparison: "«Ho incontrato un amico» diventa «non ho incontrato un amico».",
    guided: "Costruisci «Al mio compleanno ho chiesto la strada».",
    spoken: "Di' cosa non hai fatto il mese scorso.",
    recap: "Sai gestire tutte e quattro le forme di tempo e polarità.",
  },
  "places-1": {
    title: "Andare e tornare",
    objective: "Di' dove vai, cammini e torni.",
    rule: "e segna la direzione verso cui vai.",
    comparison: "Tornare a casa contrasta col camminare alla stazione.",
    guided: "Costruisci «Vado al parco della città».",
    spoken: "Di' che vai al parco.",
    recap: "Sai muoverti verso i luoghi.",
  },
  "places-2": {
    title: "Dentro e fuori, e da dove",
    objective: "Entra ed esci dai luoghi e di' da dove.",
    rule: "kara segna dove inizia il movimento.",
    comparison: "Entrare nel negozio contrasta con l'uscirne.",
    guided: "Costruisci «Vado in banca e all'ufficio postale».",
    spoken: "Di' che entri nel negozio.",
    recap: "Sai entrare, uscire e partire da un luogo.",
  },
  "places-3": {
    title: "Muoversi",
    objective: "Sali e scendi dai mezzi.",
    rule: "ni segna il mezzo su cui sali.",
    comparison: "Salire sul treno contrasta con lo scenderne.",
    guided: "Costruisci «Prendo un taxi per l'aeroporto».",
    spoken: "Di' che sali sul treno.",
    recap: "Sai usare i mezzi.",
  },
  "places-4": {
    title: "Portare e chiedere la strada",
    objective: "Porta cose e chiedi la strada.",
    rule: "Schemi familiari si combinano per chiedere indicazioni.",
    comparison: "Portare una borsa contrasta col chiedere la strada.",
    guided: "Chiedi dov'è la stazione.",
    spoken: "Chiedi dov'è la stazione.",
    recap: "Sai chiedere e rispondere sulle indicazioni.",
  },
  "people-1": {
    title: "La mia famiglia",
    objective: "Nomina i familiari e insegna a qualcuno.",
    rule: "ni segna la persona che riceve un'azione.",
    comparison: "«Questa è la mia famiglia» si restringe a «questo è mio padre».",
    guided: "Costruisci «Insegno giapponese a un amico».",
    spoken: "Di' che insegni a un amico.",
    recap: "Sai nominare la famiglia e rivolgerti alle persone.",
  },
  "people-2": {
    title: "Dare e ricevere",
    objective: "Di' a chi dai e da chi ricevi.",
    rule: "ageru dà, morau riceve e ni segna il partner.",
    comparison: "Dare una lettera contrasta col riceverne una.",
    guided: "Costruisci «Leggo un libro a mio figlio e mia figlia».",
    spoken: "Di' che dai una lettera a un amico.",
    recap: "Sai dare e ricevere.",
  },
  "people-3": {
    title: "Facciamo progetti",
    objective: "Proponi e offri azioni condivise.",
    rule: "mashou propone; mashou-ka offre.",
    comparison: "«Andiamo» diventa «la porto io?».",
    guided: "Costruisci «Mangiamo al parco».",
    spoken: "Proponi di mangiare insieme.",
    recap: "Sai organizzare semplici progetti.",
  },
  "descriptions-1": {
    title: "Grande e piccolo",
    objective: "Descrivi le cose con aggettivi in i e in na.",
    rule: "Gli aggettivi in i e in na descrivono i nomi.",
    comparison: "Una casa grande diventa una casa piccola.",
    guided: "Costruisci «Mi siedo in una stanza graziosa».",
    spoken: "Descrivi una casa piccola.",
    recap: "Sai descrivere le cose.",
  },
  "descriptions-2": {
    title: "Piaceri e antipatie",
    objective: "Di' cosa ti piace, cosa non ti piace e in cosa sei bravo.",
    rule: "ga segna ciò che ti piace o in cui sei bravo.",
    comparison: "Amare il giapponese contrasta col non amare i film.",
    guided: "Costruisci «Mi piace la musica; sono bravo in giapponese».",
    spoken: "Di' cosa ti piace.",
    recap: "Sai esprimere le preferenze.",
  },
  "descriptions-3": {
    title: "Confrontare e il meteo di ieri",
    objective: "Confronta opzioni e descrivi stati passati.",
    rule: "yori confronta; un aggettivo in i prende katta al passato.",
    comparison:
      "Cambia solo l'aggettivo: l'autobus passa da più economico a più caro del treno.",
    guided: "Costruisci «Imparo il giapponese».",
    spoken: "Di' che impari il giapponese.",
    recap: "Sai confrontare e descrivere il passato.",
  },
  "shopping-1": {
    title: "Quanti",
    objective: "Conta e scegli le quantità.",
    rule: "Un classificatore segue il nome per dare una quantità.",
    comparison: "Una mela diventa tre mele.",
    guided: "Chiedi quanto costa una maglietta.",
    spoken: "Di' che compri tre mele.",
    recap: "Sai scegliere le quantità.",
  },
  "shopping-2": {
    title: "Per favore, e vorrei",
    objective: "Fai richieste cortesi e di' cosa vuoi.",
    rule: "kudasai richiede; tai dice cosa vuoi.",
    comparison: "«Dell'acqua, per favore» diventa «voglio bere un caffè».",
    guided: "Costruisci «Voglio comprare della frutta».",
    spoken: "Chiedi dell'acqua con cortesia.",
    recap: "Sai fare richieste ed esprimere desideri.",
  },
  "shopping-3": {
    title: "Prendere in prestito, aprire, chiudere",
    objective: "Prendi in prestito, apri e chiudi le cose.",
    rule: "Le transazioni quotidiane riusano lo schema con o.",
    comparison: "Cambia solo il verbo: aprire il negozio diventa chiuderlo.",
    guided: "Costruisci «Prendo in prestito un libro da un amico».",
    spoken: "Di' che prendi in prestito un libro.",
    recap: "Sai gestire piccole transazioni.",
  },
  "existence-needs-1": {
    title: "Cosa c'è e dove",
    objective: "Di' dove sono le cose inanimate.",
    rule: "arimasu dice che una cosa esiste; le parole di posizione dicono dove.",
    comparison: "Un libro sul tavolo passa a una borsa sotto di esso.",
    guided: "Costruisci «Ci sono chiavi e occhiali accanto alla sedia».",
    spoken: "Di' che c'è un libro sul tavolo.",
    recap: "Sai localizzare le cose.",
  },
  "existence-needs-2": {
    title: "Chi c'è e dove",
    objective: "Di' dove sono le persone.",
    rule: "imasu dice che una persona o un animale esiste.",
    comparison: "Una persona dentro contrasta con un bambino davanti.",
    guided: "Costruisci «La mia famiglia è nella stanza accanto».",
    spoken: "Di' che c'è una persona nella stanza.",
    recap: "Sai localizzare le persone.",
  },
  "existence-needs-3": {
    title: "Di cosa ho bisogno",
    objective: "Esprimi bisogni immediati.",
    rule: "iru esprime un bisogno; hoshii dice che vuoi una cosa.",
    comparison: "Aver bisogno di medicine contrasta col volere acqua.",
    guided: "Costruisci «Mi servono un biglietto e un passaporto».",
    spoken: "Di' che ti serve una medicina.",
    recap: "Sai esprimere i bisogni.",
  },
  "capstones-orientation": {
    title: "Prima delle prove finali",
    objective: "Ripassa ogni ingranaggio prima delle tre prove finali.",
    rule: "Le prove finali ricombinano solo ciò che già conosci.",
    comparison: "Un'affermazione diventa una domanda con ka.",
    guided: "Costruisci «Studio giapponese ogni giorno».",
    spoken: "Presentati in una riga.",
    recap: "Sei pronto per le prove finali.",
  },
  "capstones-self-introduction": {
    title: "Prova finale: presentazione",
    objective: "Presentati e fai domande reciproche.",
    rule: "Combina identità, studio e domande in un unico scambio.",
    comparison: "Una presentazione semplice acquista una provenienza e una domanda.",
    guided: "Costruisci «Lavoro; capisci l'inglese?».",
    spoken: "Fai la tua presentazione completa.",
    recap: "Hai completato la prova finale di presentazione.",
  },
  "capstones-everyday-outing": {
    title: "Prova finale: un'uscita quotidiana",
    objective: "Coordina tempo, persone e acquisti in un'uscita.",
    rule: "Concatena trasporto, incontro e acquisto in un'unica uscita.",
    comparison: "Prendere l'autobus porta a mangiare con un amico.",
    guided: "Costruisci «Compro frutta al minimarket e torno a casa».",
    spoken: "Descrivi la tua uscita.",
    recap: "Hai completato la prova finale dell'uscita quotidiana.",
  },
  "capstones-travel-day": {
    title: "Prova finale: una giornata di viaggio",
    objective: "Spostati, usa i mezzi e risolvi un bisogno di viaggio.",
    rule: "Combina movimento, bisogni e richieste lungo un viaggio.",
    comparison: "Salire sul treno porta ad aver bisogno di una mappa.",
    guided: "Costruisci «Uso il passaporto in hotel e apro la porta».",
    spoken: "Descrivi la tua giornata di viaggio.",
    recap: "Hai completato la prova finale della giornata di viaggio.",
  },
};

const exampleTranslations: Record<string, string> = {
  "sounds-1-base": "Buongiorno.",
  "sounds-1-changed": "Buonasera.",
  "sounds-1-say": "Salve.",
  "sounds-1-r1": "Arrivederci.",
  "sounds-2-base": "Grazie.",
  "sounds-2-changed": "Scusa.",
  "sounds-2-say": "Sì.",
  "sounds-2-r1": "No.",
  "sounds-3-base": "Piacere.",
  "sounds-3-changed": "Conto su di te.",
  "sounds-3-say": "Piacere; conto su di te.",
  "sounds-4-base": "caffè",
  "sounds-4-changed": "succo",
  "sounds-4-say": "latte",
  "sounds-4-r1": "pane",
  "sounds-4-r2": "televisione",
  "sounds-5-base": "radio",
  "sounds-5-changed": "macchina fotografica",
  "sounds-5-say": "autobus",
  "sounds-5-r1": "taxi",
  "sounds-5-r2": "ristorante",
  "introductions-1-base": "Sono uno studente.",
  "introductions-1-changed": "Tu sei uno studente.",
  "introductions-1-say": "Mi chiamo Yuki.",
  "introductions-1-r1": "La mia città d'origine è il Giappone.",
  "introductions-1-r2": "Mina è un'insegnante di giapponese.",
  "introductions-2-base": "La mia città d'origine è l'Italia.",
  "introductions-2-changed": "La mia città d'origine è l'America.",
  "introductions-2-say": "Vivo in Italia.",
  "introductions-2-r1": "Sono un medico.",
  "introductions-2-r2": "Ken è un impiegato.",
  "introductions-2-r3": "Ho venticinque anni.",
  "introductions-2-r4": "Il mio Paese è il Giappone.",
  "introductions-3-base": "Studio giapponese.",
  "introductions-3-changed": "Studio inglese.",
  "introductions-3-say": "Faccio il lavoro della mia azienda.",
  "introductions-3-r1": "Capisco il giapponese.",
  "introductions-3-r2": "Studio la lingua del mio amico.",
  "introductions-3-r3": "So il numero di telefono.",
  "essential-questions-1-base": "Questo è caffè.",
  "essential-questions-1-changed": "Questo è caffè?",
  "essential-questions-1-say": "Quella macchina fotografica è giapponese?",
  "essential-questions-1-r1": "Qual è la mia macchina fotografica?",
  "essential-questions-1-r2": "quello, quello là e quella radio",
  "essential-questions-2-base": "Dov'è il ristorante?",
  "essential-questions-2-changed": "Il ristorante è qui.",
  "essential-questions-2-say": "Dove vai?",
  "essential-questions-2-r1": "Lì c'è un ristorante.",
  "essential-questions-2-r2": "Vado laggiù.",
  "essential-questions-2-r3": "Cos'è quello? Di chi è?",
  "essential-questions-3-base": "Quando vieni?",
  "essential-questions-3-changed": "Perché vieni?",
  "essential-questions-3-say": "Quanto costa questo caffè?",
  "essential-questions-3-r1": "Quanti caffè?",
  "essential-questions-3-r2": "Com'è il giapponese?",
  "actions-1-base": "Mangio un pasto.",
  "actions-1-changed": "Mangio un pasto al ristorante.",
  "actions-1-say": "Bevo acqua.",
  "actions-1-r1": "Bevo il tè al ristorante.",
  "actions-2-base": "Leggo un libro.",
  "actions-2-changed": "Guardo un film con un amico.",
  "actions-2-say": "Scrivo una lettera con un amico.",
  "actions-2-r1": "Leggo il giornale.",
  "actions-2-r2": "Leggo la lettera del mio amico.",
  "actions-3-base": "Compro una borsa.",
  "actions-3-changed": "Uso una penna.",
  "actions-3-say": "Faccio una foto.",
  "actions-3-r1": "Compro un quaderno e una matita.",
  "actions-3-r2": "Scrivo un'email.",
  "actions-3-r3": "Compro cibo e bevande.",
  "actions-3-r4": "Uso questa cosa.",
  "routines-1-base": "Mi sveglio alle sette del mattino.",
  "routines-1-changed": "Vado a dormire alle undici di sera.",
  "routines-1-say": "Faccio colazione al mattino.",
  "routines-1-r1": "Bevo il tè a mezzogiorno.",
  "routines-2-base": "Lavoro ogni giorno.",
  "routines-2-changed": "A volte parlo giapponese.",
  "routines-2-say": "Guardo sempre un film nel fine settimana.",
  "routines-2-r1": "Leggo spesso libri.",
  "routines-3-base": "Ascolto musica al mattino.",
  "routines-3-changed": "Faccio una telefonata di sera.",
  "routines-3-say": "Studio giapponese il lunedì.",
  "routines-3-r1": "Parlo con un amico la domenica.",
  "routines-3-r2": "le nove del mattino e le tre e mezza del pomeriggio",
  "routines-3-r3": "Studio giapponese per un'ora.",
  "routines-3-r4": "Guardo l'orologio.",
  "routines-3-r5": "Mi sveglio alle sei e cinque del mattino.",
  "past-negative-1-base": "Ieri ho guardato un film con un amico.",
  "past-negative-1-changed": "Oggi guardo un film con un amico.",
  "past-negative-1-say": "La settimana scorsa ho fatto un test.",
  "past-negative-1-r1": "Stamattina ho letto il giornale.",
  "past-negative-1-r2": "L'anno scorso ho studiato giapponese.",
  "past-negative-2-base": "Oggi faccio i compiti.",
  "past-negative-2-changed": "Oggi non faccio i compiti.",
  "past-negative-2-say": "Stasera non vado alla riunione.",
  "past-negative-2-r1": "La settimana prossima aspetterò un amico.",
  "past-negative-3-base": "Il mese scorso ho incontrato un amico.",
  "past-negative-3-changed": "Il mese scorso non ho incontrato un amico.",
  "past-negative-3-say": "Al mio compleanno ho chiesto la strada.",
  "past-negative-3-r1":
    "Questa settimana e questo mese sono giorni di riposo; il mese prossimo vado in Giappone; quest'anno incontro un amico.",
  "past-negative-3-r2": "L'anno prossimo, in un giorno libero, incontrerò un amico.",
  "places-1-base": "Torno a casa.",
  "places-1-changed": "Cammino fino alla stazione.",
  "places-1-say": "Vado al parco della città.",
  "places-1-r1": "Torno a casa da scuola.",
  "places-2-base": "Entro nel negozio.",
  "places-2-changed": "Esco dal negozio.",
  "places-2-say": "Vado in banca e all'ufficio postale.",
  "places-2-r1": "Cammino dall'ospedale.",
  "places-2-r2": "Leggo un libro in biblioteca.",
  "places-3-base": "Salgo sul treno alla stazione.",
  "places-3-changed": "Scendo dal treno alla stazione.",
  "places-3-say": "Prendo un taxi per l'aeroporto.",
  "places-3-r1": "Vado in metropolitana e in autobus.",
  "places-3-r2": "auto, bicicletta e aereo",
  "places-4-base": "Porto una borsa.",
  "places-4-changed": "Chiedo la strada alla stazione.",
  "places-4-say": "Dov'è la stazione?",
  "places-4-r1": "Uso il computer nella stanza.",
  "people-1-base": "Questa è la mia famiglia.",
  "people-1-changed": "Questa persona è mio padre.",
  "people-1-say": "Insegno giapponese a un amico.",
  "people-1-r1": "Mia madre, mia sorella maggiore e mia sorella minore sono la famiglia.",
  "people-1-r2": "I miei fratelli maggiore e minore sono studenti.",
  "people-1-r3": "I miei genitori camminano nel parco.",
  "people-2-base": "Do una lettera a un amico.",
  "people-2-changed": "Ricevo una lettera da mio padre.",
  "people-2-say": "Leggo un libro a mio figlio e mia figlia.",
  "people-2-r1": "Questi sono mio nonno e mia nonna.",
  "people-2-r2": "Marito e moglie guardano un film.",
  "people-2-r3": "Insegno giapponese ai bambini.",
  "people-3-base": "Andiamo al parco con un amico.",
  "people-3-changed": "La porto io la borsa?",
  "people-3-say": "Mangiamo al parco.",
  "people-3-r1": "Lui e lei sono amici.",
  "people-3-r2": "L'uomo e la donna sono insegnanti.",
  "people-3-r3": "Aspetto il bambino e la bambina.",
  "descriptions-1-base": "È una casa grande.",
  "descriptions-1-changed": "È una casa piccola.",
  "descriptions-1-say": "Mi siedo in una stanza graziosa.",
  "descriptions-1-r1": "un'auto nuova e una bicicletta vecchia",
  "descriptions-1-r2": "Questo libro è interessante.",
  "descriptions-1-r3": "Il lavoro difficile è divertente.",
  "descriptions-2-base": "Mi piace il giapponese.",
  "descriptions-2-changed": "Non mi piacciono i film.",
  "descriptions-2-say": "Mi piace la musica; sono bravo in giapponese.",
  "descriptions-2-r1": "Questo cibo è delizioso.",
  "descriptions-2-r2": "Il tempo di oggi è bello.",
  "descriptions-3-base": "L'autobus costa meno del treno.",
  "descriptions-3-changed": "L'autobus costa più del treno.",
  "descriptions-3-say": "Imparo il giapponese.",
  "descriptions-3-r1": "Il tempo è caldo; pioggia e nuvole.",
  "descriptions-3-r2": "Sto in piedi davanti all'insegnante.",
  "descriptions-3-r3": "Il lavoro facile è stato divertente.",
  "descriptions-3-r7": "Ieri faceva freddo.",
  "shopping-1-base": "Compro una mela.",
  "shopping-1-changed": "Compro tre mele.",
  "shopping-1-say": "Quanto costa questa maglietta?",
  "shopping-1-r1": "Compro due uova e un po' di carne.",
  "shopping-1-r2": "Compro tutta la verdura e il pesce.",
  "shopping-2-base": "Dell'acqua, per favore.",
  "shopping-2-changed": "Voglio bere un caffè.",
  "shopping-2-say": "Voglio comprare della frutta.",
  "shopping-2-r1": "Mezzo tè, per favore.",
  "shopping-2-r2": "Compro molta frutta al supermercato.",
  "shopping-3-base": "Apro il negozio.",
  "shopping-3-changed": "Chiudo il negozio.",
  "shopping-3-say": "Prendo in prestito un libro da un amico.",
  "shopping-3-r1": "Ho usato tutti i soldi del portafoglio.",
  "shopping-3-r2": "Il prezzo dei vestiti è alto.",
  "shopping-3-r3": "Chiedo tre cappelli e la taglia.",
  "shopping-3-r4": "mille yen e cento yen",
  "existence-needs-1-base": "C'è un libro sul tavolo.",
  "existence-needs-1-changed": "C'è una borsa sotto il tavolo.",
  "existence-needs-1-say": "Ci sono chiavi e occhiali accanto alla sedia.",
  "existence-needs-1-r1": "Ci sono occhiali sulla sedia.",
  "existence-needs-1-r2": "C'è un'auto fuori.",
  "existence-needs-2-base": "C'è una persona nella stanza.",
  "existence-needs-2-changed": "C'è un bambino davanti alla casa.",
  "existence-needs-2-say": "La mia famiglia è nella stanza accanto.",
  "existence-needs-2-r1": "dietro, destra, sinistra e in mezzo",
  "existence-needs-2-r2": "Un amico è vicino alla stazione.",
  "existence-needs-3-base": "Ho bisogno di medicine.",
  "existence-needs-3-changed": "Voglio dell'acqua.",
  "existence-needs-3-say": "Mi servono un biglietto e un passaporto.",
  "existence-needs-3-r1": "Mi servono una mappa e un ombrello.",
  "existence-needs-3-r2": "C'è un bagno in hotel.",
  "capstones-orientation-base": "Sono uno studente di giapponese.",
  "capstones-orientation-changed": "Sono uno studente di giapponese?",
  "capstones-orientation-say": "Studio giapponese ogni giorno.",
  "capstones-self-introduction-base": "Piacere, sono Yuki.",
  "capstones-self-introduction-changed": "La mia città d'origine è l'Italia; parlo giapponese.",
  "capstones-self-introduction-say": "Lavoro; capisci l'inglese?",
  "capstones-self-introduction-r1": "Vivo in una casa; la mia famiglia è qui.",
  "capstones-self-introduction-r2": "Incontro un amico; imparo il giapponese.",
  "capstones-self-introduction-r3":
    "Voglio studiare il giapponese; non parlo inglese.",
  "capstones-everyday-outing-base": "Prendo l'autobus; vado in città.",
  "capstones-everyday-outing-changed": "Mangio con un amico al ristorante.",
  "capstones-everyday-outing-say":
    "Compro frutta al minimarket; torno a casa.",
  "capstones-everyday-outing-r1": "Cammino nel parco; faccio foto.",
  "capstones-everyday-outing-r2":
    "Aspetto un amico alla stazione; guardiamo un film.",
  "capstones-everyday-outing-r3": "Ascolto musica; chiamo un amico.",
  "capstones-everyday-outing-r4":
    "Il treno costa meno del taxi; il film è stato divertente.",
  "capstones-everyday-outing-r5": "Faccio una foto?",
  "capstones-travel-day-base":
    "Salgo sull'aereo all'aeroporto; scendo dal treno alla stazione.",
  "capstones-travel-day-changed": "Chiedo la strada; mi serve una mappa.",
  "capstones-travel-day-say": "Uso il passaporto in hotel; apro la porta.",
  "capstones-travel-day-r1": "Prendo in prestito un ombrello; porto una borsa.",
  "capstones-travel-day-r2": "Entro in hotel; chiudo la finestra.",
  "capstones-travel-day-r3": "Torno a casa; scrivo un'email a un amico.",
  "capstones-travel-day-r4":
    "Un biglietto, per favore; non ho capito la strada.",
  "past-negative-1-r3": "Stamattina mi sono svegliato; ho scritto una lettera; ho letto il giornale.",
  "past-negative-2-r2": "Stasera non lavoro; non dormo.",
  "past-negative-3-r3": "Ho parlato con un amico; ho ascoltato musica; ho fatto una telefonata.",
  "places-1-r2": "Il mio amico vive in città; parla giapponese.",
  "places-4-r2": "Aspetto un amico alla stazione; faccio una foto.",
  "people-1-r4": "Un amico viene a casa; scrivo una lettera.",
  "people-1-r5": "Mio nonno vive in Giappone; ascolta musica.",
  "people-2-r4": "Chiamo un amico; insegno delle parole.",
  "people-2-r5": "Capisco le parole del bambino.",
  "people-3-r4": "Incontro un amico in città; porto una borsa.",
  "descriptions-1-r4": "Al mattino mi sveglio; ogni giorno lavoro; di notte dormo.",
  "descriptions-2-r3": "Do un libro a un amico; ricevo un libro da mio padre.",
  "descriptions-3-r4": "Insegno giapponese ai bambini; faccio una foto.",
  "shopping-1-r3": "Entro nel negozio; compro delle scarpe; esco dal negozio.",
  "shopping-2-r3": "Salgo sul treno alla stazione; scendo all'aeroporto.",
  "shopping-2-r4": "Al negozio do dei soldi a un amico; ricevo il resto.",
  "shopping-3-r5": "Torno a casa dal negozio; imparo il giapponese.",
  "shopping-3-r6": "Sto in piedi sul treno; mi siedo sulla sedia.",
  "shopping-3-r7": "Ogni giorno lavoro al negozio; prendo in prestito un libro da un amico.",
  "shopping-3-r8": "Apro il portafoglio; chiudo il portafoglio.",
  "existence-needs-1-r3": "Mi siedo sulla sedia; leggo un libro.",
  "existence-needs-1-r4": "Scendo dal treno alla stazione; porto una borsa.",
  "existence-needs-2-r3": "Sto in piedi davanti alla porta; apro la porta.",
  "existence-needs-2-r4": "Un amico viene alla stazione; incontro l'amico.",
  "existence-needs-3-r3": "In hotel prendo in prestito un ombrello; chiudo la finestra.",
  "existence-needs-3-r4": "Entro in hotel; esco dalla stanza.",
  "existence-needs-3-r5": "Do una medicina a un amico; ricevo una mappa da mio padre.",
  "existence-needs-3-r6": "Insegno giapponese ai bambini; imparo il giapponese.",
  "descriptions-3-r5": "Di notte dormo alle dieci.",
  "people-3-r5": "Esco dal negozio; porto una borsa.",
  "existence-needs-2-r5": "Mio nonno si siede sulla sedia.",
  "existence-needs-3-r7": "Sto in piedi davanti alla finestra.",
  "routines-3-r6": "Domani studio giapponese.",
  "past-negative-3-r5": "Sono andato alla festa di compleanno.",
  "descriptions-2-r4": "Oggi sono impegnato.",
  "descriptions-3-r6": "Questa macchina fotografica è cara.",
};

// Locale-independent instruction copy for the deterministic exercises (Slice C
// plan Task 2). The intent text of a construction exercise reuses the target
// example's own translation, so no meaning string is duplicated here.
const exercisePrompts: Record<string, string> = {
  "exercise.prompt.order": "Riordina le tessere nella frase corretta.",
  "exercise.prompt.particle": "Scegli la particella che completa la frase.",
  "exercise.prompt.ending": "Scegli la desinenza corretta del predicato.",
  "exercise.prompt.complete": "Scrivi la parte mancante della frase.",
  "exercise.prompt.construct": "Scrivi questa frase in giapponese.",
  "exercise.prompt.transform.past": "Riscrivi la frase al passato.",
  "exercise.prompt.transform.negative": "Riscrivi la frase alla forma negativa.",
  "exercise.prompt.transform.past-negative":
    "Riscrivi la frase al passato negativo.",
};

function build(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [id, copy] of Object.entries(modules)) {
    out[`module.${id}.title`] = copy.title;
    out[`module.${id}.outcome`] = copy.outcome;
  }
  for (const [id, copy] of Object.entries(lessons)) {
    for (const field of LESSON_FIELDS) {
      out[`lesson.${id}.${field}`] = copy[field];
    }
  }
  for (const example of curriculumExamples) {
    out[`example.${example.id}.translation`] = exampleTranslations[example.id];
  }
  for (const [id, text] of Object.entries(exercisePrompts)) {
    out[id] = text;
  }
  return out;
}

/** Italian learner-facing copy, keyed identically to the English catalog. */
export const it: Readonly<Record<string, string>> = Object.freeze(build());
