import { deepFreeze } from "../../foundations/deepFreeze";

export type HistoricalActivityDispositionKind = "same-semantics" | "historical-orphan";

export interface V4ActivityMigrationRow {
  readonly sourceLevel: "a1";
  readonly sourceLessonId: string;
  readonly sourceActivityId: string;
  readonly destinationLevel: "a0";
  readonly destinationLessonId: string;
  readonly destinationActivityId: string | null;
  readonly disposition: HistoricalActivityDispositionKind;
}

/**
 * Explicit V4 activity disposition registry. Base replacements intentionally
 * receive new activity ids, so no changed-semantics V4 activity can satisfy
 * a future Base requirement.
 */
export const V4_ACTIVITY_MIGRATION_MAP: readonly V4ActivityMigrationRow[] = deepFreeze([
  { sourceLevel: "a1", sourceLessonId: "sounds-1", sourceActivityId: "snd1-a-ex", destinationLevel: "a0", destinationLessonId: "sounds-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-1", sourceActivityId: "snd1-i-ex", destinationLevel: "a0", destinationLessonId: "sounds-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-1", sourceActivityId: "snd1-u-ex", destinationLevel: "a0", destinationLessonId: "sounds-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-1", sourceActivityId: "snd1-e-ex", destinationLevel: "a0", destinationLessonId: "sounds-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-2", sourceActivityId: "snd2-ka-ex", destinationLevel: "a0", destinationLessonId: "sounds-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-2", sourceActivityId: "snd2-ga-ex", destinationLevel: "a0", destinationLessonId: "sounds-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-2", sourceActivityId: "snd2-ki-ex", destinationLevel: "a0", destinationLessonId: "sounds-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-2", sourceActivityId: "snd2-gi-ex", destinationLevel: "a0", destinationLessonId: "sounds-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-3", sourceActivityId: "snd3-kite-ex", destinationLevel: "a0", destinationLessonId: "sounds-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-3", sourceActivityId: "snd3-kitte-ex", destinationLevel: "a0", destinationLessonId: "sounds-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-3", sourceActivityId: "snd3-obasan-ex", destinationLevel: "a0", destinationLessonId: "sounds-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-3", sourceActivityId: "snd3-obaasan-ex", destinationLevel: "a0", destinationLessonId: "sounds-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-4", sourceActivityId: "snd4-koohii-ex", destinationLevel: "a0", destinationLessonId: "sounds-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-4", sourceActivityId: "snd4-terebi-ex", destinationLevel: "a0", destinationLessonId: "sounds-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-4", sourceActivityId: "snd4-pan-ex", destinationLevel: "a0", destinationLessonId: "sounds-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sounds-4", sourceActivityId: "snd4-resutoran-ex", destinationLevel: "a0", destinationLessonId: "sounds-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-1", sourceActivityId: "sentence-foundations-1-round-1::sentence-foundations-1-m1", destinationLevel: "a0", destinationLessonId: "sentence-foundations-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-1", sourceActivityId: "sentence-foundations-1-round-2::sentence-foundations-1-t3", destinationLevel: "a0", destinationLessonId: "sentence-foundations-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-1", sourceActivityId: "sentence-foundations-1-round-1::sentence-foundations-1-m8", destinationLevel: "a0", destinationLessonId: "sentence-foundations-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-1", sourceActivityId: "sentence-foundations-1-round-2::sentence-foundations-1-t2", destinationLevel: "a0", destinationLessonId: "sentence-foundations-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-2", sourceActivityId: "sentence-foundations-2-round-1::sentence-foundations-2-m6", destinationLevel: "a0", destinationLessonId: "sentence-foundations-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-2", sourceActivityId: "sentence-foundations-2-round-2::sentence-foundations-2-t1", destinationLevel: "a0", destinationLessonId: "sentence-foundations-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-2", sourceActivityId: "sentence-foundations-2-round-1::sentence-foundations-2-m8", destinationLevel: "a0", destinationLessonId: "sentence-foundations-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-2", sourceActivityId: "sentence-foundations-2-round-2::sentence-foundations-2-t2", destinationLevel: "a0", destinationLessonId: "sentence-foundations-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-3", sourceActivityId: "sentence-foundations-3-round-1::sentence-foundations-3-m3", destinationLevel: "a0", destinationLessonId: "sentence-foundations-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-3", sourceActivityId: "sentence-foundations-3-round-2::sentence-foundations-3-t3", destinationLevel: "a0", destinationLessonId: "sentence-foundations-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-3", sourceActivityId: "sentence-foundations-3-round-1::sentence-foundations-3-m8", destinationLevel: "a0", destinationLessonId: "sentence-foundations-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-3", sourceActivityId: "sentence-foundations-3-round-2::sentence-foundations-3-t2", destinationLevel: "a0", destinationLessonId: "sentence-foundations-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-4", sourceActivityId: "sentence-foundations-4-round-1::sentence-foundations-4-m2", destinationLevel: "a0", destinationLessonId: "sentence-foundations-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-4", sourceActivityId: "sentence-foundations-4-round-2::sentence-foundations-4-t2", destinationLevel: "a0", destinationLessonId: "sentence-foundations-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-4", sourceActivityId: "sentence-foundations-4-round-1::sentence-foundations-4-m1", destinationLevel: "a0", destinationLessonId: "sentence-foundations-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "sentence-foundations-4", sourceActivityId: "sentence-foundations-4-round-2::sentence-foundations-4-t3", destinationLevel: "a0", destinationLessonId: "sentence-foundations-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-1", sourceActivityId: "topic-questions-1-round-1::topic-questions-1-m7", destinationLevel: "a0", destinationLessonId: "topic-questions-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-1", sourceActivityId: "topic-questions-1-round-2::topic-questions-1-t5", destinationLevel: "a0", destinationLessonId: "topic-questions-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-1", sourceActivityId: "topic-questions-1-round-1::topic-questions-1-m6", destinationLevel: "a0", destinationLessonId: "topic-questions-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-1", sourceActivityId: "topic-questions-1-round-2::topic-questions-1-t3", destinationLevel: "a0", destinationLessonId: "topic-questions-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-2", sourceActivityId: "topic-questions-2-round-1::topic-questions-2-m6", destinationLevel: "a0", destinationLessonId: "topic-questions-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-2", sourceActivityId: "topic-questions-2-round-2::topic-questions-2-t5", destinationLevel: "a0", destinationLessonId: "topic-questions-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-2", sourceActivityId: "topic-questions-2-round-1::topic-questions-2-m7", destinationLevel: "a0", destinationLessonId: "topic-questions-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-2", sourceActivityId: "topic-questions-2-round-2::topic-questions-2-t4", destinationLevel: "a0", destinationLessonId: "topic-questions-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-3", sourceActivityId: "topic-questions-3-round-1::topic-questions-3-m2", destinationLevel: "a0", destinationLessonId: "topic-questions-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-3", sourceActivityId: "topic-questions-3-round-2::topic-questions-3-t1", destinationLevel: "a0", destinationLessonId: "topic-questions-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-3", sourceActivityId: "topic-questions-3-round-1::topic-questions-3-m1", destinationLevel: "a0", destinationLessonId: "topic-questions-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-3", sourceActivityId: "topic-questions-3-round-2::topic-questions-3-t3", destinationLevel: "a0", destinationLessonId: "topic-questions-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-4", sourceActivityId: "topic-questions-4-round-1::topic-questions-4-m1", destinationLevel: "a0", destinationLessonId: "topic-questions-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-4", sourceActivityId: "topic-questions-4-round-2::topic-questions-4-t2", destinationLevel: "a0", destinationLessonId: "topic-questions-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-4", sourceActivityId: "topic-questions-4-round-1::topic-questions-4-m8", destinationLevel: "a0", destinationLessonId: "topic-questions-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "topic-questions-4", sourceActivityId: "topic-questions-4-round-2::topic-questions-4-t5", destinationLevel: "a0", destinationLessonId: "topic-questions-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-1", sourceActivityId: "polite-verbs-1-round-1::polite-verbs-1-m1", destinationLevel: "a0", destinationLessonId: "polite-verbs-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-1", sourceActivityId: "polite-verbs-1-round-2::polite-verbs-1-t5", destinationLevel: "a0", destinationLessonId: "polite-verbs-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-1", sourceActivityId: "polite-verbs-1-round-1::polite-verbs-1-m8", destinationLevel: "a0", destinationLessonId: "polite-verbs-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-1", sourceActivityId: "polite-verbs-1-round-2::polite-verbs-1-t4", destinationLevel: "a0", destinationLessonId: "polite-verbs-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-2", sourceActivityId: "polite-verbs-2-round-1::polite-verbs-2-m2", destinationLevel: "a0", destinationLessonId: "polite-verbs-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-2", sourceActivityId: "polite-verbs-2-round-2::polite-verbs-2-t1", destinationLevel: "a0", destinationLessonId: "polite-verbs-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-2", sourceActivityId: "polite-verbs-2-round-1::polite-verbs-2-m8", destinationLevel: "a0", destinationLessonId: "polite-verbs-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-2", sourceActivityId: "polite-verbs-2-round-2::polite-verbs-2-t2", destinationLevel: "a0", destinationLessonId: "polite-verbs-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-3", sourceActivityId: "polite-verbs-3-round-1::polite-verbs-3-m7", destinationLevel: "a0", destinationLessonId: "polite-verbs-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-3", sourceActivityId: "polite-verbs-3-round-2::polite-verbs-3-t1", destinationLevel: "a0", destinationLessonId: "polite-verbs-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-3", sourceActivityId: "polite-verbs-3-round-1::polite-verbs-3-m8", destinationLevel: "a0", destinationLessonId: "polite-verbs-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-3", sourceActivityId: "polite-verbs-3-round-2::polite-verbs-3-t3", destinationLevel: "a0", destinationLessonId: "polite-verbs-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-4", sourceActivityId: "polite-verbs-4-round-1::polite-verbs-4-m2", destinationLevel: "a0", destinationLessonId: "polite-verbs-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-4", sourceActivityId: "polite-verbs-4-round-2::polite-verbs-4-t2", destinationLevel: "a0", destinationLessonId: "polite-verbs-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-4", sourceActivityId: "polite-verbs-4-round-1::polite-verbs-4-m1", destinationLevel: "a0", destinationLessonId: "polite-verbs-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "polite-verbs-4", sourceActivityId: "polite-verbs-4-round-2::polite-verbs-4-t3", destinationLevel: "a0", destinationLessonId: "polite-verbs-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-1", sourceActivityId: "time-movement-1-round-1::time-movement-1-m1", destinationLevel: "a0", destinationLessonId: "time-movement-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-1", sourceActivityId: "time-movement-1-round-2::time-movement-1-t4", destinationLevel: "a0", destinationLessonId: "time-movement-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-1", sourceActivityId: "time-movement-1-round-1::time-movement-1-m8", destinationLevel: "a0", destinationLessonId: "time-movement-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-1", sourceActivityId: "time-movement-1-round-2::time-movement-1-t5", destinationLevel: "a0", destinationLessonId: "time-movement-1", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-2", sourceActivityId: "time-movement-2-round-1::time-movement-2-m1", destinationLevel: "a0", destinationLessonId: "time-movement-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-2", sourceActivityId: "time-movement-2-round-2::time-movement-2-t5", destinationLevel: "a0", destinationLessonId: "time-movement-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-2", sourceActivityId: "time-movement-2-round-1::time-movement-2-m8", destinationLevel: "a0", destinationLessonId: "time-movement-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-2", sourceActivityId: "time-movement-2-round-2::time-movement-2-t4", destinationLevel: "a0", destinationLessonId: "time-movement-2", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-3", sourceActivityId: "time-movement-3-round-1::time-movement-3-m7", destinationLevel: "a0", destinationLessonId: "time-movement-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-3", sourceActivityId: "time-movement-3-round-2::time-movement-3-t2", destinationLevel: "a0", destinationLessonId: "time-movement-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-3", sourceActivityId: "time-movement-3-round-1::time-movement-3-m6", destinationLevel: "a0", destinationLessonId: "time-movement-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-3", sourceActivityId: "time-movement-3-round-2::time-movement-3-t3", destinationLevel: "a0", destinationLessonId: "time-movement-3", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-4", sourceActivityId: "time-movement-4-round-1::time-movement-4-m7", destinationLevel: "a0", destinationLessonId: "time-movement-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-4", sourceActivityId: "time-movement-4-round-2::time-movement-4-t3", destinationLevel: "a0", destinationLessonId: "time-movement-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-4", sourceActivityId: "time-movement-4-round-1::time-movement-4-m8", destinationLevel: "a0", destinationLessonId: "time-movement-4", destinationActivityId: null, disposition: "historical-orphan" },
  { sourceLevel: "a1", sourceLessonId: "time-movement-4", sourceActivityId: "time-movement-4-round-2::time-movement-4-t2", destinationLevel: "a0", destinationLessonId: "time-movement-4", destinationActivityId: null, disposition: "historical-orphan" },
]);
